'use client';
import { useState } from 'react';
import { formatProductionJobOption, type ProductionJobOption } from '@/modules/production/job-options';
import type { PurchaseOrderLine } from './types';
import { allocationError } from './allocation-model';
export default function LineAllocations({ line, jobs, onChange }: { line: PurchaseOrderLine; jobs: ProductionJobOption[]; onChange(line: PurchaseOrderLine): void }) {
 const [open, setOpen] = useState(false);
 const rows = line.allocations ?? [], allocated = rows.reduce((sum, row) => sum + (Number(row.quantity) || 0), 0);
 const remainder = Number(line.details.quantityOrdered) - allocated, unit = line.details.orderUnit || 'order units';
 const error = allocationError(line);
 return <div className="m-3 border-t border-slate-200 pt-3"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="min-h-9 border border-slate-400 px-3 text-xs font-bold">Allocate</button><span className="text-xs text-slate-600">{rows.length ? `${allocated} ${unit} · ${rows.length} Job reservation${rows.length > 1 ? 's' : ''}` : 'Entirely unallocated'} · {Math.max(0, remainder)} {unit} general stock</span></div>{error && <p role="alert" className="mt-2 text-xs text-red-700">{error}</p>}{open && <div className="mt-3 space-y-2"><p className="text-xs text-slate-600">Allocate in the PO quantity unit ({unit}), not package contents. Receipt creates Job-reserved stock. The remainder stays general stock; document-level Job context does not allocate it.</p>{rows.map((row, i) => <div key={i} className="flex flex-wrap gap-2"><select aria-label={`Allocation ${i + 1} Job`} value={row.productionJobId} onChange={e => onChange({ ...line, allocations: rows.map((r, n) => n === i ? { ...r, productionJobId: e.target.value } : r) })} className="min-h-10 min-w-0 flex-1 border bg-white px-2 text-sm"><option value="">Select Production Job</option>{jobs.map(job => <option key={job.id} value={job.id}>{formatProductionJobOption(job)}</option>)}</select><input aria-label={`Allocation ${i + 1} quantity`} type="number" min="0" step="0.000001" value={row.quantity} onChange={e => onChange({ ...line, allocations: rows.map((r, n) => n === i ? { ...r, quantity: e.target.value } : r) })} className="min-h-10 w-28 border bg-white px-2 text-sm"/><button type="button" onClick={() => onChange({ ...line, allocations: rows.filter((_, n) => n !== i) })} className="min-h-10 px-2 text-xs underline">Remove allocation {i + 1}</button></div>)}<button type="button" onClick={() => onChange({ ...line, allocations: [...rows, { productionJobId: '', quantity: '' }] })} className="min-h-9 border px-3 text-xs">Add Job allocation</button></div>}</div>;
}
