import Image from 'next/image';
import type { PurchaseOrderPrintModel } from './print-model';

const label = 'text-[8px] font-bold uppercase tracking-[0.08em] text-slate-700';
const value = 'mt-1 whitespace-pre-line text-[10px] leading-4 text-black';
export default function PurchaseOrderDocument({ model }: { model: PurchaseOrderPrintModel }) {
  const rows = [...model.lines, ...Array.from({ length: Math.max(0, 12 - model.lines.length) }, (_, index) => ({ item: model.lines.length + index + 1, sku: '', description: '', quantity: '', unit: '', unitPrice: '', lineTotal: '' }))];
  return <article className="relative mx-auto min-h-[11in] w-[8.5in] overflow-hidden bg-white px-[0.42in] py-[0.36in] font-sans text-black shadow-2xl print:shadow-none">
    {model.status === 'DRAFT' && <div className="pointer-events-none absolute inset-0 flex items-center justify-center text-[84px] font-black tracking-[0.12em] text-slate-200/60 -rotate-35">DRAFT</div>}
    <div className="relative z-10">
      <header className="grid grid-cols-[1.35fr_1fr] border-b-2 border-slate-900 pb-2"><div className="flex items-center gap-3"><Image src="/logo.png" alt="Tenarten Terrazzo" width={80} height={80} className="h-20 w-20 object-contain grayscale"/><div><div className="text-[19px] font-black tracking-wide">TENARTEN TERRAZZO LLC</div><div className="text-[10px] font-bold uppercase tracking-[0.1em]">Precast Manufacturing</div><div className="mt-1 text-[9px] leading-4">2933 Eisenhower St., Suite 120<br/>Carrollton, TX 75007<br/>469-491-7002 · www.precasttz.com<br/>sales@tenartenterrazzo.com</div></div></div><div><div className="text-right text-[24px] font-light tracking-[0.12em]">PURCHASE ORDER</div><div className="mt-3 grid grid-cols-3 border border-slate-700"><div className="p-2"><div className={label}>PO Date</div><div className={value}>{model.poDate}</div></div><div className="border-x border-slate-700 p-2"><div className={label}>PO Originated By</div><div className={value}>{model.originatedBy}</div></div><div className="p-2"><div className={label}>PO #</div><div className={`${value} font-bold`}>{model.poNumber}</div></div></div></div></header>
      <div className="mt-2 bg-slate-800 py-1 text-center text-[9px] font-bold uppercase tracking-[0.18em] text-white">Vendor Information</div>
      <section className="grid min-h-24 grid-cols-2 border-x border-b border-slate-700"><div className="p-2"><div className={label}>Vendor Name</div><div className={`${value} font-bold`}>{model.vendorName}</div><div className={`${value} mt-2`}>{model.vendorAddress}</div></div><div className="border-l border-slate-700 p-2"><div className={label}>Contact</div><div className={value}>{model.vendorContact}</div></div></section>
      <div className="mt-2 bg-slate-800 py-1 text-center text-[9px] font-bold uppercase tracking-[0.18em] text-white">Project Information</div>
      <section className="grid grid-cols-3 border-x border-b border-slate-700"><div className="p-2"><div className={label}>Job Reference</div><div className={value}>{model.jobReference}</div><div className={`${label} mt-3`}>Payment Terms</div><div className={value}>{model.paymentTerms}</div></div><div className="border-x border-slate-700 p-2"><div className={label}>Job Number</div><div className={value}>{model.jobNumber}</div><div className={`${label} mt-3`}>Date Requested</div><div className={value}>{model.requestedDate}</div></div><div className="p-2"><div className={label}>Ship To:</div><div className={value}>{model.shipTo}</div></div></section>
      <table className="mt-2 w-full table-fixed border-collapse text-[9px]"><colgroup><col className="w-[5%]"/><col className="w-[13%]"/><col className="w-[43%]"/><col className="w-[9%]"/><col className="w-[8%]"/><col className="w-[11%]"/><col className="w-[11%]"/></colgroup><thead><tr className="bg-slate-800 text-white"><th className="border border-slate-700 p-1">ITEM</th><th className="border border-slate-700 p-1">SKU</th><th className="border border-slate-700 p-1 text-left">DESCRIPTION</th><th className="border border-slate-700 p-1">QTY</th><th className="border border-slate-700 p-1">UNIT</th><th className="border border-slate-700 p-1">UNIT PRICE</th><th className="border border-slate-700 p-1">TOTAL</th></tr></thead><tbody>{rows.map(row => <tr key={row.item} className="h-7 align-top"><td className="border border-slate-400 p-1 text-center">{row.item}</td><td className="border border-slate-400 p-1">{row.sku}</td><td className="border border-slate-400 p-1 font-medium">{row.description}</td><td className="border border-slate-400 p-1 text-right">{row.quantity}</td><td className="border border-slate-400 p-1 text-center">{row.unit}</td><td className="border border-slate-400 p-1 text-right">{row.unitPrice}</td><td className="border border-slate-400 p-1 text-right">{row.lineTotal}</td></tr>)}</tbody></table>
      <section className="grid grid-cols-[1.55fr_1fr] border-x border-b border-slate-700"><div className="p-2"><div className={label}>Additional Notes &amp; Special Conditions</div><div className={`${value} min-h-24`}>{model.notes}</div></div><dl className="border-l border-slate-700 text-[9px]"><div className="flex justify-between border-b border-slate-400 px-2 py-1.5"><dt>Subtotal</dt><dd>{model.subtotal}</dd></div><div className="flex justify-between border-b border-slate-400 px-2 py-1.5"><dt>Discount @ {model.discountPercent || '—'}%</dt><dd>{model.discountAmount}</dd></div><div className="flex justify-between border-b border-slate-400 px-2 py-1.5"><dt>Taxable Subtotal</dt><dd>{model.taxableSubtotal}</dd></div><div className="flex justify-between border-b border-slate-400 px-2 py-1.5"><dt>Sales Tax @ {model.taxPercent || '—'}%</dt><dd>{model.taxAmount}</dd></div><div className="flex justify-between border-b border-slate-400 px-2 py-1.5"><dt>Freight</dt><dd>{model.freight}</dd></div><div className="flex justify-between bg-slate-100 px-2 py-2 text-[11px] font-bold"><dt>Total</dt><dd>{model.total}</dd></div></dl></section>
      <section className="ml-auto mt-2 w-[40%] border border-slate-700 p-2"><div className={label}>Authorized By:</div><div className={value}>{model.authorizedBy}</div></section>
      <footer className="mt-4 border-t border-slate-400 pt-2 text-center text-[8px] leading-3">Please contact us promptly if any of the items noted on this purchase order cannot be fulfilled as listed and shipped by the date requested, thank you!</footer>
    </div>
  </article>;
}
