'use client';

import { Settings2 } from 'lucide-react';
import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { createPurchaseOrderDraft } from './defaults';
import { loadProductionJobOption } from '@/modules/production/job-options';
import { loadPurchaseOrder,loadPurchaseOrderSummaries } from './queries';
import type { PurchaseOrderDraft,PurchaseOrderStatus,PurchaseOrderSummary } from './types';
import { PurchaseOrderEditor } from './PurchaseOrderEditor';
import VendorManager from './VendorManager';

const filters:Array<'all'|PurchaseOrderStatus>=['all','draft','issued','superseded'];
const statusLabel=(value:'all'|PurchaseOrderStatus)=>value==='superseded'?'Prior Revisions':value;

export default function PurchasingWorkspace(){
  const [orders,setOrders]=useState<PurchaseOrderSummary[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [search,setSearch]=useState(''); const [filter,setFilter]=useState<'all'|PurchaseOrderStatus>('all');
  const [editor,setEditor]=useState<PurchaseOrderDraft|null>(null); const [manageVendors,setManageVendors]=useState(false);
  const handledLaunch=useRef(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setOrders(await loadPurchaseOrderSummaries());}catch(caught){setError(caught instanceof Error?caught.message:'Unable to load Purchase Orders.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(handledLaunch.current)return;handledLaunch.current=true;const jobId=new URLSearchParams(window.location.search).get('jobId');if(!jobId)return;loadProductionJobOption(jobId).then(job=>{if(!job){setMessage('The requested Production job was not found. You can still create an unlinked Purchase Order.');setEditor(createPurchaseOrderDraft());return;}const next=createPurchaseOrderDraft();next.productionJobId=job.id;next.jobNumberSnapshot=job.job_number||'';next.jobNameSnapshot=job.name||'';next.requestedDate=job.requested_delivery_date||'';next.lines=next.lines.map(line=>({...line,details:{...line.details,productionJobId:job.id}}));setEditor(next);}).catch(()=>{setMessage('The Production job could not be loaded. You can still create an unlinked Purchase Order.');setEditor(createPurchaseOrderDraft());});},[]);
  const visible=useMemo(()=>orders.filter(order=>(filter==='all'||order.status===filter)&&`${order.poNumber||''} ${order.vendorNameSnapshot} ${order.orderDate} ${order.status}`.toLowerCase().includes(search.toLowerCase())),[orders,filter,search]);
  const edit=async(id:string)=>{try{const po=await loadPurchaseOrder(id);if(po.status==='cancelled'||po.status==='superseded'){setError('Cancelled and prior-revision Purchase Orders cannot be opened in this pass.');return;}setEditor({id:po.id,poNumber:po.poNumber||'',status:po.status,documentTemplate:po.documentTemplate||'tenops',revisionNumber:po.revisionNumber,supersedesPurchaseOrderId:po.supersedesPurchaseOrderId,revisionReason:po.revisionReason,productionJobId:po.productionJobId,jobNumberSnapshot:po.jobNumberSnapshot,jobNameSnapshot:po.jobNameSnapshot,vendorId:po.vendorId,vendorNameSnapshot:po.vendorNameSnapshot,vendorAddressSnapshot:po.vendorAddressSnapshot,vendorContactSnapshot:po.vendorContactSnapshot,shipToSnapshot:po.shipToSnapshot,paymentTermsSnapshot:po.paymentTermsSnapshot,authorizedBySnapshot:po.authorizedBySnapshot,orderDate:po.orderDate,requestedDate:po.requestedDate,currency:po.currency,discountPercent:po.discountPercent,taxPercent:po.taxPercent,freight:po.freight,commercialNotes:po.commercialNotes,internalNotes:po.internalNotes,createdBy:po.createdBy,updatedBy:po.updatedBy,updatedAt:po.updatedAt,issuedAt:po.issuedAt,issuedBy:po.issuedBy,issuanceId:po.issuanceId,snapshotHash:po.snapshotHash,lines:po.lines});}catch(caught){setError(caught instanceof Error?caught.message:'Unable to open Purchase Order.');}};
  const completed=(kind:'saved'|'deleted')=>{setEditor(null);setMessage(kind==='saved'?'Purchase Order draft saved.':'Purchase Order draft and its lines were deleted.');void load();};
  return <div className="min-h-[calc(100vh-73px)] bg-[#eef1f4] px-3 py-5 text-slate-950 sm:px-5"><div className="mx-auto max-w-[1600px]">
    <header className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-4"><div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Purchasing</div><h1 className="mt-1 text-3xl font-bold">Purchase Orders</h1><p className="mt-1 text-sm text-slate-600">Structured chip and aggregate purchasing drafts.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setManageVendors(true)} className="inline-flex h-9 items-center gap-2 border border-slate-400 bg-white px-4 text-sm font-bold"><Settings2 className="h-4 w-4"/>Vendors &amp; Contacts</button><button type="button" onClick={()=>setEditor(createPurchaseOrderDraft())} className="h-9 bg-slate-900 px-4 text-sm font-bold text-white">+ New Purchase Order</button></div></header>
    {message&&<div role="status" className="mt-4 border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{message}</div>}
    <section className="mt-4 overflow-hidden rounded-sm border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b border-slate-200 p-3"><input value={search} onChange={event=>setSearch(event.target.value)} className="h-9 min-w-[260px] flex-1 border border-slate-300 px-3 text-sm" placeholder="Search PO number, vendor, date, or status"/><div className="inline-flex divide-x divide-slate-300 border border-slate-300">{filters.map(value=><button key={value} type="button" onClick={()=>setFilter(value)} className={`h-9 px-3 text-xs font-bold uppercase ${filter===value?'bg-slate-900 text-white':'bg-white text-slate-600'}`}>{statusLabel(value)}</button>)}</div></div>
      {error&&<div className="border-b border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
      {loading?<div className="p-6 text-sm text-slate-500">Loading Purchase Orders…</div>:visible.length===0?<div className="p-8 text-center text-sm text-slate-500">No matching Purchase Orders. Create the first chip purchasing draft when ready.</div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-600"><tr><th className="px-3 py-2">PO</th><th className="px-3 py-2">Vendor</th><th className="px-3 py-2">Order Date</th><th className="px-3 py-2">Requested</th><th className="px-3 py-2">Status</th><th className="px-3 py-2 text-right">Lines</th><th className="px-3 py-2 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-200">{visible.map(order=><tr key={order.id} onClick={()=>void edit(order.id)} className="cursor-pointer hover:bg-slate-50"><td className="px-3 py-3 font-bold">{order.poNumber||'Unnumbered draft'}</td><td className="px-3 py-3">{order.vendorNameSnapshot}</td><td className="px-3 py-3">{order.orderDate}</td><td className="px-3 py-3">{order.requestedDate||'—'}</td><td className="px-3 py-3"><span className="border border-slate-300 bg-slate-50 px-2 py-1 text-[10px] font-bold uppercase">{statusLabel(order.status)}</span></td><td className="px-3 py-3 text-right">{order.lineCount}</td><td className="px-3 py-3 text-right font-bold">{order.currency} {Number(order.total).toFixed(2)}</td></tr>)}</tbody></table></div>}
    </section><div className="mt-3 text-xs text-slate-500">Draft and issued Purchase Orders. Issued records retain permanent snapshot-generated PDFs; Pending Receivals and Inventory changes are not active.</div>
  </div>{editor&&<PurchaseOrderEditor initial={editor} onClose={()=>setEditor(null)} onSaved={()=>completed('saved')} onDeleted={()=>completed('deleted')} onIssued={()=>{setMessage('Purchase Order issued.');void load();}}/>} {manageVendors&&<VendorManager onClose={()=>setManageVendors(false)} onChanged={()=>setMessage('Vendor configuration updated.')}/>}</div>;
}
