'use client';

import type { JobUpdateSummary, ProductionIntegrationSummary } from '../jobs';
import { materialStatusLabel } from '../material-status';
import { getJobReadiness } from '../readiness';
import type { ProductionJob } from '../types';
import ProductionStatusBadge from './ProductionStatusBadge';
import ActivityStrip from './ActivityStrip';
import { useLanguage } from '@/lib/language';

type Props = { jobs: ProductionJob[]; selectedJobId: string | null; attachmentCounts: Record<string, number>; integrationSummaries: Record<string, ProductionIntegrationSummary>; jobUpdateSummaries: Record<string, JobUpdateSummary>; onSelectJob(job: ProductionJob, focus?: string): void };

function formatHours(value: number) {
  return new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 }).format(value);
}

export default function ProductionQueue({ jobs, selectedJobId, attachmentCounts, integrationSummaries, jobUpdateSummaries, onSelectJob }: Props) {
  const { language, tr } = useLanguage();
  const materialLabels = { unknown: 'Sin definir', not_ready: 'No listo', ordered: 'Pedido', ready: 'Listo' } as const;
  return <div className="overflow-hidden rounded-sm border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(260px,1.7fr)_125px_160px_140px_150px_145px] gap-2 border-b border-slate-200 bg-slate-100/80 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.09em] text-slate-600 md:grid"><span>{tr('Job', 'Trabajo')}</span><span>{tr('Status', 'Estado')}</span><span>{tr('Schedule', 'Programación')}</span><span>{tr('Delivery', 'Entrega')}</span><span>{tr('Operations', 'Operaciones')}</span><span>{tr('Planning', 'Planificación')}</span></div><div className="divide-y divide-slate-200">
    {jobs.map((job) => { const readiness = getJobReadiness(job); const setupFocus = readiness.state === 'not_scheduled' ? 'planned-dates' : readiness.missing.includes('labor estimate') ? 'labor' : undefined; const fileCount = attachmentCounts[job.id] ?? 0; const updateSummary = jobUpdateSummaries[job.id] ?? { total: 0, openFollowUpCount: 0, latestCreatedAt: null }; const summary = integrationSummaries[job.id] ?? { actualHours: 0, laborEntryCount: 0, materialReportDates: [] }; const hasMaterialUse = summary.materialReportDates.length > 0; return <div key={job.id} className={`relative grid grid-cols-1 items-center gap-2 px-4 py-3 hover:bg-slate-50 md:grid-cols-[minmax(260px,1.7fr)_125px_160px_140px_150px_145px] ${selectedJobId === job.id ? 'bg-blue-50/70 ring-2 ring-inset ring-blue-600' : ''}`}>
      <button type="button" aria-label={`Open ${job.name}`} onClick={() => onSelectJob(job, setupFocus)} className="absolute inset-0 z-0 outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-700"><span className="sr-only">Open job details</span></button>
      <span className="pointer-events-none relative z-10 min-w-0"><span className="block text-sm font-bold leading-5">{job.job_number && <span className="mr-2 text-slate-500">{job.job_number}</span>}{job.name}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{job.customer || tr('Customer not recorded', 'Cliente no registrado')}</span><ActivityStrip job={job} attachmentCount={fileCount} updateSummary={updateSummary} onOpenAttachments={() => onSelectJob(job, 'attachments')} onOpenUpdates={() => onSelectJob(job, 'job-updates')} />{job.archived_at ? <span className="mt-1 inline-block text-[10px] font-bold uppercase text-slate-500">{tr('Archived', 'Archivado')}</span> : null}</span>
      <span className="pointer-events-none relative z-10"><ProductionStatusBadge status={job.production_status} /></span>
      <span className="pointer-events-none relative z-10 text-xs">{job.planned_start && job.planned_end ? `${job.planned_start} – ${job.planned_end}` : 'Dates not set'}</span>
      <span className="pointer-events-none relative z-10 text-xs">{job.requested_delivery_date ? `Delivery ${job.requested_delivery_date}` : 'Delivery not set'}</span>
      <span className="relative z-10 flex flex-col items-start gap-1 text-[10px]">
        {job.estimated_man_hours !== null ? <span className="pointer-events-none flex items-baseline gap-1 text-slate-500"><strong className="text-xs text-slate-800">{formatHours(job.estimated_man_hours)}h</strong><span>{tr('Estimated', 'Estimadas')}</span></span> : <span className="pointer-events-none px-0.5 py-1 font-semibold text-slate-900">{tr('No Labor Estimate', 'Sin estimación de mano de obra')}</span>}
        {summary.laborEntryCount > 0 ? <button type="button" aria-label={`${tr('Open manpower reporting for', 'Abrir reporte de mano de obra para')} ${job.name}`} onClick={() => { window.location.href = `/manpower-reporting?job=${job.id}`; }} className="inline-flex h-6 cursor-pointer items-center rounded-sm border border-blue-200 bg-blue-50 px-1.5 font-bold text-blue-900 shadow-sm transition hover:-translate-y-px hover:border-blue-300 hover:bg-blue-100 hover:shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">{formatHours(summary.actualHours)}h {tr('Current', 'Registradas')}</button> : <span className="pointer-events-none px-0.5 py-1 font-semibold text-slate-900">{tr('No Labor Reports', 'Sin reportes de mano de obra')}</span>}
        {hasMaterialUse ? <button type="button" data-operational-tone="success" aria-label={`${tr('Open material usage for', 'Abrir uso de materiales para')} ${job.name}`} onClick={() => { window.location.href = `/material-usage?historyJob=${job.id}&openReportJob=${job.id}`; }} className="inline-flex h-6 cursor-pointer items-center rounded-sm border border-emerald-200 bg-emerald-100 px-1.5 font-bold text-emerald-800 shadow-sm transition hover:-translate-y-px hover:border-emerald-300 hover:bg-emerald-200 hover:shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-700">{tr('Material Use', 'Uso de materiales')}</button> : <button type="button" data-operational-tone="warning" aria-label={`${tr('Create material usage report for', 'Crear reporte de materiales para')} ${job.name}`} onClick={() => { window.location.href = `/material-usage?newJob=${job.id}`; }} className="inline-flex h-6 cursor-pointer items-center rounded-sm border border-amber-200 bg-amber-100 px-1.5 font-bold text-amber-900 shadow-sm transition hover:-translate-y-px hover:border-amber-300 hover:bg-amber-200 hover:shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-700">{tr('No Material Use Linked', 'Sin reporte de materiales')}</button>}
      </span>
      <span className={`pointer-events-none relative z-10 text-xs font-bold ${readiness.state === 'ready' ? 'text-green-700' : 'text-amber-800'}`}>{language === 'es' ? readiness.state === 'ready' ? 'Planificación completa' : 'Requiere planificación' : readiness.label}<span className="block font-normal text-slate-500">{tr('Material Status', 'Estado de materiales')}: {language === 'es' ? materialLabels[job.material_status] : materialStatusLabel(job.material_status)}</span></span>
    </div>; })}
    {!jobs.length && <div className="px-4 py-10 text-center text-sm text-slate-600">{tr('No jobs match the current view.', 'Ningún trabajo coincide con la vista actual.')}</div>}
  </div></div>;
}
