import {createClient} from 'npm:@supabase/supabase-js@2.101.1';
import {PDFDocument,StandardFonts,rgb} from 'npm:pdf-lib@1.17.1';
import{buildProposalPdfModel,paginateProposalPdf,PROPOSAL_ESCALATION_NOTICE,PROPOSAL_LEAD_TIME_NOTICE,PROPOSAL_PDF_VERSION,wrapProposalText}from'./proposal-pdf-model.ts';
import{tenartenLogo}from'./tenarten-logo.ts';

const allowed=(Deno.env.get('TENOPS_ALLOWED_ORIGINS')||'http://localhost:3000').split(',').map(v=>v.trim()).filter(Boolean);
const cors=(origin:string)=>({'Access-Control-Allow-Origin':allowed.includes(origin)?origin:allowed[0]||'http://localhost:3000','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Vary':'Origin'});
const json=(body:unknown,status:number,headers:Record<string,string>)=>new Response(JSON.stringify(body),{status,headers:{...headers,'Content-Type':'application/json'}});
const safe=(value:unknown)=>String(value??'').replace(/^Delivery$/,'Requested delivery date').replaceAll('—','-').replaceAll('–','-').replace(/[^\x20-\x7e\n]/g,'?');

export async function render(snapshot:Record<string,unknown>){
  const model=buildProposalPdfModel(snapshot);const pdf=await PDFDocument.create();const logo=await pdf.embedPng(tenartenLogo);pdf.setTitle(`Estimate ${model.estimateNumber}`);pdf.setAuthor('Tenarten Terrazzo Co.');pdf.setProducer(`TenOps ${PROPOSAL_PDF_VERSION}`);
  const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const navy=rgb(.04,.10,.22),ink=rgb(.06,.08,.12),gray=rgb(.35,.38,.43),pale=rgb(.94,.95,.96),red=rgb(.75,.05,.05);
  const layout=paginateProposalPdf(model,{measureText:(value:string,size:number)=>regular.widthOfTextAtSize(safe(value),size)});const money=(number:number)=>`$ ${number.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const columns=[{key:'itemNumber',label:'Item',x:32,width:20},{key:'description',label:'Description',x:52,width:167},{key:'ref',label:'REF',x:219,width:30},{key:'colorPlate',label:'COLOR PLATE',x:249,width:38,headerSize:4.5},{key:'quantity',label:'QTY',x:287,width:22},{key:'unit',label:'',x:309,width:18},{key:'length',label:'L',x:327,width:25},{key:'width',label:'W',x:352,width:25},{key:'heightThickness',label:'H/T',x:377,width:29},{key:'cft',label:'CFT',x:406,width:26},{key:'lf',label:'LF',x:432,width:24},{key:'estimatedWeight',label:'EST. weight',x:456,width:36,headerSize:4.5},{key:'rate',label:'Rate',x:492,width:40},{key:'total',label:'Total',x:532,width:48}] as const;
  for(const pageLayout of layout){
    const page=pdf.addPage([612,792]);const text=(value:unknown,x:number,y:number,size=7,font=regular,color=ink)=>page.drawText(safe(value),{x,y,size,font,color});const rect=(x:number,y:number,width:number,height:number,fill=rgb(1,1,1))=>page.drawRectangle({x,y,width,height,color:fill,borderColor:gray,borderWidth:.55});const wrapped=(value:unknown,x:number,y:number,width:number,size=7,max=8,font=regular,color=ink)=>{const lines:string[]=[];for(const paragraph of safe(value).split('\n')){let current='';for(const word of paragraph.split(/\s+/).filter(Boolean)){const candidate=current?`${current} ${word}`:word;if(font.widthOfTextAtSize(candidate,size)<=width)current=candidate;else{if(current)lines.push(current);current=word;}if(lines.length>=max)break;}if(current&&lines.length<max)lines.push(current);if(lines.length>=max)break;}lines.forEach((line,index)=>text(line,x,y-index*(size+2),size,font,color));};
    if(pageLayout.pageNumber===1){
      page.drawImage(logo,{x:32,y:700,width:66,height:67.55});text('Tenarten Terrazzo Co.',106,752,15,bold,navy);text('PRECAST MANUFACTURING',106,738,7,bold);text('2933 Eisenhower St., Suite 120',106,725);text('Carrollton, TX 75007',106,714);text('www.precasttz.com',106,703,7,regular,navy);text('Estimate',478,750,18,bold,ink);rect(478,716,102,22);if(model.revised)text('REVISED',500,723,10,bold,red);page.drawLine({start:{x:32,y:693},end:{x:580,y:693},thickness:1.5,color:navy});
      rect(32,610,274,73);rect(306,610,274,73);text('Name / Address',39,671,6,bold,gray);wrapped([model.customerName,model.customerAddress,model.customerContact].filter(Boolean).join('\n'),39,657,255,7.5,6);[['Date',model.proposalDate],['Estimate #',model.estimateNumber],['Valid for',`${model.validDays} days`],['Delivery',model.requestedDelivery]].forEach(([label,value],index)=>{text(label,315,670-index*15,6,bold,gray);text(value,390,670-index*15,7.2,index===1?bold:regular);});
      [['F.O.B.',model.fob],['Side Mark',model.sideMark],['Sales Rep',model.salesRep],['Terms',model.terms]].forEach(([label,value],index)=>{const x=32+(index%2)*137,y=580-Math.floor(index/2)*30;rect(x,y,137,30,pale);text(label,x+6,y+18,6,bold,gray);text(value,x+6,y+7,7,bold);});rect(306,550,274,60);page.drawLine({start:{x:306,y:580},end:{x:580,y:580},thickness:.55,color:gray});[[PROPOSAL_ESCALATION_NOTICE,594],[PROPOSAL_LEAD_TIME_NOTICE,564]].forEach(([notice,top])=>{const lines=wrapProposalText(notice,254,6,(candidate,size)=>bold.widthOfTextAtSize(candidate,size)).slice(0,3);lines.forEach((line,index)=>text(line,316+(254-bold.widthOfTextAtSize(line,6))/2,top-index*8,6,bold));});const[materialDisclaimer,...dimensionDisclaimerParts]=safe(model.disclaimer).split(/\n\s*\n/);rect(32,506,274,44);rect(306,506,274,44);wrapped(materialDisclaimer,39,535,258,5.4,4);wrapped(dimensionDisclaimerParts.join(' '),313,535,258,5.4,4);
    }else{
      text('Tenarten Terrazzo Co.',32,754,12,bold,navy);text(`Estimate ${model.estimateNumber}`,365,754,11,bold,navy);text(`${model.projectNumber}${model.projectNumber&&model.projectName?' - ':''}${model.projectName}`,32,737,7,bold);text(`Page ${pageLayout.pageNumber} of ${pageLayout.pageCount}`,500,737,7,regular,gray);if(model.revised)text('REVISED',501,718,9,bold,red);page.drawLine({start:{x:32,y:710},end:{x:580,y:710},thickness:1.2,color:navy});
    }
    const tableTop=pageLayout.pageNumber===1?498:690;if(pageLayout.repeatTableHeader)for(const column of columns){rect(column.x,tableTop,column.width,22,pale);if(column.label)text(column.label,column.x+3,tableTop+8,'headerSize'in column?column.headerSize:6,bold,navy);}let y=tableTop;
    for(const row of pageLayout.rows){y-=row.height;for(const column of columns)rect(column.x,y,column.width,row.height);const line=row.line;text(line.itemNumber,35,y+row.height-13,6.5);row.descriptionLines.forEach((part:string,index:number)=>text(part,56,y+row.height-13-index*9,6.4));text(line.ref,222,y+row.height-13,6);text(line.colorPlate,252,y+row.height-13,5.5);text(line.quantity,290,y+row.height-13,6);text(line.unit,312,y+row.height-13,6);text(line.length,330,y+row.height-13,5.7);text(line.width,355,y+row.height-13,5.7);text(line.heightThickness,380,y+row.height-13,5.7);text(line.cft,409,y+row.height-13,5.7);text(line.lf,435,y+row.height-13,5.7);text(line.estimatedWeight,459,y+row.height-13,5.7);text(line.lineType==='included'?'INCL':line.lineType==='informational'?'':money(line.rate),495,y+row.height-13,5.5);text(line.lineType==='included'?'INCL':line.lineType==='informational'?'':money(line.total),535,y+row.height-13,5.5,bold);}
    if(pageLayout.notesLines.length&&!pageLayout.closing){text('NOTES / CLARIFICATIONS',32,680,7,bold,navy);pageLayout.notesLines.forEach((line:string,index:number)=>text(line,32,666-index*8,6.2));}
    if(pageLayout.closing){const closingTop=pageLayout.rows.length?Math.min(y-12,210+pageLayout.notesLines.length*8):650;rect(32,closingTop-64,360,64);text('FORMULA / COLOR',39,closingTop-15,6.5,bold,navy);wrapped(model.formula,39,closingTop-27,345,6.2,5);rect(392,closingTop-64,188,64);[['Subtotal',model.subtotal],[model.taxEnabled?`Tax (${model.taxRate}%)`:'Tax',model.tax],['TOTAL',model.total]].forEach(([label,value],index)=>{text(label,402,closingTop-18-index*18,7,index===2?bold:regular);text(money(Number(value)),492,closingTop-18-index*18,7,index===2?bold:regular);});let noteY=closingTop-83;if(pageLayout.notesLines.length){text('NOTES / CLARIFICATIONS',32,noteY,7,bold,navy);noteY-=13;pageLayout.notesLines.forEach((line:string,index:number)=>text(line,32,noteY-index*8,6.2));}text('Quote respectfully submitted by:',32,66,7,regular,gray);text(model.submittedByName||'Anthony Iorio',32,53,8,bold);text([model.submittedByPhone,model.submittedByEmail].filter(Boolean).join(' | '),32,41,6.5,regular,navy);text('Purchase approved by:',355,66,7);page.drawLine({start:{x:350,y:49},end:{x:500,y:49},thickness:.6,color:gray});page.drawLine({start:{x:515,y:49},end:{x:580,y:49},thickness:.6,color:gray});text('Customer Signature',355,33,7);text('Date',520,33,7);}
  }
  return new Uint8Array(await pdf.save());
}

Deno.serve(async(req)=>{const origin=req.headers.get('origin')||'';const headers=cors(origin);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});try{const auth=req.headers.get('authorization')||'';if(!auth)return json({error:'Authentication required.'},401,headers);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:access,error:accessError}=await user.rpc('has_proposal_access');if(accessError||access!==true)return json({error:'Proposal access denied.'},403,headers);const body=await req.json();const action=String(body.action||'');if(action==='preview'){const bytes=await render(body.snapshot);return new Response(bytes,{headers:{...headers,'Content-Type':'application/pdf','Content-Disposition':'inline; filename="Proposal-Preview.pdf"'}});}const id=String(body.proposalId||'');if(!/^[0-9a-f-]{36}$/i.test(id))return json({error:'Invalid Proposal.'},400,headers);const service=createClient(url,serviceKey);
  if(action==='delete'){
    const{data:identity}=await user.auth.getUser();const userId=identity.user?.id;
    const[{data:admin},{count:revisions},{data:pdf}]=await Promise.all([
      service.from('app_users').select('role,is_active').eq('user_id',userId||'').maybeSingle(),
      service.from('proposals').select('id',{count:'exact',head:true}).eq('prior_proposal_id',id),
      service.from('proposal_pdf_documents').select('storage_bucket,storage_path').eq('proposal_id',id).maybeSingle(),
    ]);
    if(admin?.role!=='admin'||admin?.is_active!==true)return json({error:'Only an active Admin may delete an issued Proposal.'},403,headers);
    if((revisions??0)>0)return json({error:'A Proposal with revisions cannot be deleted.'},409,headers);
    if(pdf?.storage_path){const removed=await service.storage.from(String(pdf.storage_bucket||'proposal-documents')).remove([String(pdf.storage_path)]);if(removed.error)return json({error:'The generated Proposal PDF could not be removed; no records were deleted.'},500,headers);}
    const{error:deleteError}=await user.rpc('admin_delete_issued_proposal',{p_proposal_id:id});if(deleteError)throw deleteError;
    return json({deleted:true},200,headers);
  }
  const{data:proposal,error}=await service.from('proposals').select('issued_snapshot,estimate_number,status').eq('id',id).single();if(error||proposal?.status!=='issued'||!proposal.issued_snapshot)return json({error:'Issued Proposal not found.'},404,headers);const path=`${id}/${String(proposal.estimate_number).replace(/[^A-Za-z0-9._-]/g,'-')}.pdf`;if(action==='generate'){await service.from('proposal_pdf_documents').update({status:'generating',last_error:null}).eq('proposal_id',id);try{const bytes=await render(proposal.issued_snapshot);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(value=>value.toString(16).padStart(2,'0')).join('');const upload=await service.storage.from('proposal-documents').upload(path,bytes,{contentType:'application/pdf',upsert:true});if(upload.error)throw upload.error;await service.from('proposal_pdf_documents').update({status:'generated',storage_path:path,snapshot_hash:hash,generated_at:new Date().toISOString(),last_error:null}).eq('proposal_id',id);}catch(cause){await service.from('proposal_pdf_documents').update({status:'failed',last_error:cause instanceof Error?cause.message:'PDF generation failed.'}).eq('proposal_id',id);throw cause;}}const signed=await service.storage.from('proposal-documents').createSignedUrl(path,3600);if(signed.error)return json({error:'Proposal PDF is unavailable.'},404,headers);return json({url:signed.data.signedUrl},200,headers);}catch(cause){return json({error:cause instanceof Error?cause.message:'Proposal PDF request failed.'},500,headers);}});
