// @ts-nocheck -- Shared pure model accepts both database snake_case and UI camelCase snapshots.
export const PROPOSAL_PDF_VERSION='proposal-pdf-v1';
const value=(source,camel,snake=camel)=>String(source?.[camel]??source?.[snake]??'');
const number=(source,camel,snake=camel)=>{const parsed=Number(source?.[camel]??source?.[snake]??0);return Number.isFinite(parsed)?parsed:0;};
export function buildProposalPdfModel(snapshot){
 if(!snapshot||typeof snapshot!=='object')throw new Error('Proposal snapshot is required.');
 const lines=Array.isArray(snapshot.lines)?snapshot.lines:[];
 const model={estimateNumber:value(snapshot,'estimateNumber','estimate_number'),versionMinor:number(snapshot,'versionMinor','version_minor'),proposalDate:value(snapshot,'proposalDate','proposal_date'),customerName:value(snapshot,'customerName','customer_name'),customerAddress:value(snapshot,'customerAddress','customer_address'),customerContact:value(snapshot,'customerContact','customer_contact'),projectName:value(snapshot,'projectName','project_name'),projectNumber:value(snapshot,'projectNumber','project_number'),projectLocation:value(snapshot,'projectLocation','project_location'),sideMark:value(snapshot,'sideMark','side_mark'),salesRep:value(snapshot,'salesRep','sales_rep'),terms:value(snapshot,'terms'),validDays:value(snapshot,'validDays','valid_days'),requestedDelivery:value(snapshot,'requestedDelivery','requested_delivery'),fob:value(snapshot,'fob'),destinationZip:value(snapshot,'destinationZip','destination_zip'),taxCounty:value(snapshot,'taxCounty','tax_county'),submittedByName:value(snapshot,'submittedByName','submitted_by_name'),submittedByPhone:value(snapshot,'submittedByPhone','submitted_by_phone'),submittedByEmail:value(snapshot,'submittedByEmail','submitted_by_email'),notes:value(snapshot,'notes'),disclaimer:value(snapshot,'disclaimerSnapshot','disclaimer_snapshot'),formula:value(snapshot,'formulaSnapshot','formula_snapshot'),taxEnabled:Boolean(snapshot.taxEnabled??snapshot.tax_enabled),taxRate:number(snapshot,'taxRate','tax_rate'),subtotal:number(snapshot,'subtotal'),tax:number(snapshot,'tax'),total:number(snapshot,'total'),lines:lines.map((line,index)=>{const lineType=value(line,'lineType','line_type')||'product';return{itemNumber:value(line,'itemNumber','item_number')||(lineType==='product'?String(index+1):''),lineType,description:value(line,'description'),ref:value(line,'ref'),colorPlate:value(line,'colorPlate','color_plate'),quantity:value(line,'quantity'),unit:value(line,'unit'),length:value(line,'length'),width:value(line,'width'),heightThickness:value(line,'heightThickness','height_thickness'),cft:value(line,'cft'),lf:value(line,'lf'),estimatedWeight:value(line,'estimatedWeight','estimated_weight'),rate:number(line,'rate'),total:number(line,'total')}})};
 if(!model.estimateNumber)throw new Error('Estimate number is required.');
 const subtotal=Math.round(model.lines.reduce((sum,line)=>sum+line.total,0)*100)/100;const tax=model.taxEnabled?Math.round(subtotal*model.taxRate)/100:0;
 return{...model,subtotal,tax,total:Math.round((subtotal+tax)*100)/100,revised:model.versionMinor>0,notesClarifications:model.notes};
}

const defaultMeasure=(value,size)=>String(value??'').length*size*.52;
export function wrapProposalText(value,width,size=6.4,measure=defaultMeasure){const lines=[];for(const paragraph of String(value??'').split('\n')){let current='';for(const word of paragraph.split(/\s+/).filter(Boolean)){const candidate=current?`${current} ${word}`:word;if(measure(candidate,size)<=width)current=candidate;else{if(current)lines.push(current);current=word;}}if(current)lines.push(current);}return lines.length?lines:[''];}
export function paginateProposalPdf(model,options={}){
 const measure=options.measureText??defaultMeasure;const descriptionWidth=options.descriptionWidth??155;const rowFontSize=options.rowFontSize??6.4;const lineHeight=options.lineHeight??9;const minRowHeight=options.minRowHeight??34;const firstCapacity=options.firstRowsHeight??350;const continuationCapacity=options.continuationRowsHeight??620;const closingHeight=options.closingHeight??150;
 const rows=model.lines.map((line,sourceIndex)=>{const descriptionLines=wrapProposalText(line.description,descriptionWidth,rowFontSize,measure);const height=Math.max(minRowHeight,16+descriptionLines.length*lineHeight);if(height>continuationCapacity)throw new Error(`Proposal line ${sourceIndex+1} is too tall to fit on one page.`);return{line,sourceIndex,height,descriptionLines};});
 const pages=[];let page={continuation:false,rows:[],usedHeight:0,capacity:firstCapacity,closing:false};pages.push(page);
 for(const row of rows){if(page.rows.length&&page.usedHeight+row.height>page.capacity){page={continuation:true,rows:[],usedHeight:0,capacity:continuationCapacity,closing:false};pages.push(page);}page.rows.push(row);page.usedHeight+=row.height;}
 let final=pages.at(-1);if(!final)throw new Error('Proposal pagination failed.');const notesLines=model.notesClarifications?wrapProposalText(model.notesClarifications,530,6.2,measure):[];const noteLineHeight=8;const rowPageNoteLimit=20;const emptyPageNoteLimit=Math.max(1,Math.floor((continuationCapacity-closingHeight)/noteLineHeight));
 if(final.capacity-final.usedHeight<closingHeight+Math.min(notesLines.length,rowPageNoteLimit)*noteLineHeight||notesLines.length>rowPageNoteLimit){const chunks=[];const remaining=[...notesLines];while(remaining.length>emptyPageNoteLimit)chunks.push(remaining.splice(0,emptyPageNoteLimit));chunks.push(remaining);for(const chunk of chunks){const next={continuation:true,rows:[],usedHeight:0,capacity:continuationCapacity,closing:false,notesLines:chunk};pages.push(next);}final=pages.at(-1);}else final.notesLines=notesLines;
 final.closing=true;
 return pages.map((entry,index)=>({...entry,notesLines:entry.notesLines??[],pageNumber:index+1,pageCount:pages.length,repeatTableHeader:entry.rows.length>0,showIdentity:index>0,showRevised:model.revised,showTotals:entry.closing}));
}
