"use client";

import { ArrowLeft, BriefcaseBusiness, FileText, Inbox, Link2, MessageSquarePlus, Paperclip, Send, Sparkles, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import Image from "next/image";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import { openProductionJob } from "@/modules/production/job-options";
import { isTenOpsSystemInboxUser, loadInboxMessages, markInboxConversationRead, openInboxAttachment, sendInboxMessage, sendInboxMessageWithAttachments, type InboxAttachment, type InboxMessage } from "./inbox";
import type { WorkCollaborator, WorkJob } from "./types";

type Conversation={userId:string;name:string;role:string;isSystem:boolean;messages:InboxMessage[];latest:InboxMessage;unread:number};
const timeLabel=(value:string)=>new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(value));
const conversationTime=(value:string)=>new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));
const dayLabel=(value:string)=>new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(new Date(value));
const dayKey=(value:string)=>new Date(value).toDateString();
const jobLabel=(job:WorkJob)=>[job.jobNumber,job.name].filter(Boolean).join(" · ");
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map((part)=>part[0]?.toUpperCase()).join("")||"?";
const fileSize=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
const attachmentAccept="image/*,.pdf,.txt,.csv,.doc,.docx,.xls,.xlsx,.ppt,.pptx";

function AttachmentView({attachment,onError,onPreview}:{attachment:InboxAttachment;onError:(message:string)=>void;onPreview:(attachment:InboxAttachment)=>void}){
  if(attachment.contentType.startsWith("image/")&&attachment.previewUrl)return <button type="button" onClick={()=>onPreview(attachment)} className="mt-2 block max-w-64 overflow-hidden rounded border border-slate-200 bg-slate-100"><Image unoptimized src={attachment.previewUrl} alt={attachment.originalFilename} width={512} height={384} className="max-h-48 h-auto w-full object-contain" /></button>;
  return <button type="button" onClick={()=>void openInboxAttachment(attachment).catch((caught)=>onError(caught instanceof Error?caught.message:"Unable to open attachment."))} className="mt-2 flex max-w-full items-center gap-2 rounded border border-slate-200 bg-white px-2 py-2 text-left"><FileText className="h-4 w-4 shrink-0 text-slate-500" /><span className="min-w-0"><span className="block truncate text-xs font-medium text-slate-800">{attachment.originalFilename}</span><span className="block text-[10px] text-slate-500">{fileSize(attachment.byteSize)}</span></span></button>;
}

export default function InboxDialog({open,onClose,currentUserId,collaborators,jobs,initialUserId="",startNewMessage=false,onUnreadChange}:{open:boolean;onClose:()=>void;currentUserId:string;collaborators:WorkCollaborator[];jobs:WorkJob[];initialUserId?:string;startNewMessage?:boolean;onUnreadChange:(count:number)=>void}){
  const auth=useAuth();
  const[messages,setMessages]=useState<InboxMessage[]>([]);const[selectedUserId,setSelectedUserId]=useState("");const[newMessage,setNewMessage]=useState(false);const[recipientId,setRecipientId]=useState("");
  const[body,setBody]=useState("");const[jobId,setJobId]=useState("");const[jobPickerOpen,setJobPickerOpen]=useState(false);const[jobQuery,setJobQuery]=useState("");const[files,setFiles]=useState<File[]>([]);
  const[sending,setSending]=useState(false);const[error,setError]=useState("");const[preview,setPreview]=useState<InboxAttachment|null>(null);
  const closeRef=useRef<HTMLButtonElement>(null);const composeRef=useRef<HTMLTextAreaElement>(null);const historyRef=useRef<HTMLDivElement>(null);const initialUserHandledRef=useRef("");

  const load=useCallback(async()=>{if(!auth.profile?.isActive)return;try{const next=await loadInboxMessages();setMessages(next);onUnreadChange(next.filter((message)=>message.recipientUserId===currentUserId&&!message.readAt).length);setError("");}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load Inbox.");}},[auth.profile?.isActive,currentUserId,onUnreadChange]);
  const conversations=useMemo(()=>{const grouped=new Map<string,InboxMessage[]>();for(const message of messages){const other=message.senderUserId===currentUserId?message.recipientUserId:message.senderUserId;grouped.set(other,[...(grouped.get(other)??[]),message]);}return[...grouped.entries()].map(([userId,entries]):Conversation=>{const latest=entries.at(-1)!;const participant=collaborators.find((user)=>user.userId===userId);const isSystem=isTenOpsSystemInboxUser(userId);return{userId,name:isSystem?"TenOps":participant?.displayName||(latest.senderUserId===userId?latest.senderName:latest.recipientName),role:isSystem?"System":participant?.role??"",isSystem,messages:entries,latest,unread:entries.filter((item)=>item.recipientUserId===currentUserId&&!item.readAt).length};}).sort((left,right)=>new Date(right.latest.createdAt).getTime()-new Date(left.latest.createdAt).getTime()||left.userId.localeCompare(right.userId));},[collaborators,currentUserId,messages]);
  const selected=conversations.find((item)=>item.userId===selectedUserId);const linkedJob=jobs.find((job)=>job.id===jobId);const jobMatches=useMemo(()=>{const query=jobQuery.trim().toLowerCase();return(query?jobs.filter((job)=>jobLabel(job).toLowerCase().includes(query)):jobs).slice(0,30);},[jobQuery,jobs]);
  const resetComposer=useCallback(()=>{setBody("");setJobId("");setJobPickerOpen(false);setJobQuery("");setFiles([]);},[]);
  const chooseConversation=useCallback((userId:string)=>{setSelectedUserId(userId);setNewMessage(false);setRecipientId(userId);resetComposer();},[resetComposer]);

  useEffect(()=>{if(!open)return;void load();closeRef.current?.focus();},[load,open]);
  useEffect(()=>{if(!open){initialUserHandledRef.current="";return;}if(initialUserId&&initialUserHandledRef.current!==initialUserId){initialUserHandledRef.current=initialUserId;chooseConversation(initialUserId);}},[chooseConversation,initialUserId,open]);
  useEffect(()=>{if(!open||!startNewMessage)return;setNewMessage(true);setSelectedUserId("");setRecipientId("");resetComposer();},[open,resetComposer,startNewMessage]);
  useEffect(()=>{if(!open||!currentUserId)return;const refresh=()=>void load();const channel=supabase.channel(`my-work-inbox:${currentUserId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"my_work_messages",filter:`recipient_user_id=eq.${currentUserId}`},refresh).on("postgres_changes",{event:"INSERT",schema:"public",table:"my_work_messages",filter:`sender_user_id=eq.${currentUserId}`},refresh).on("postgres_changes",{event:"UPDATE",schema:"public",table:"my_work_messages",filter:`recipient_user_id=eq.${currentUserId}`},refresh).subscribe();return()=>{void supabase.removeChannel(channel);};},[currentUserId,load,open]);
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(preview)setPreview(null);else onClose();};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[onClose,open,preview]);
  useEffect(()=>{if(newMessage)composeRef.current?.focus();},[newMessage]);
  useEffect(()=>{if(!open||!selectedUserId)return;const unread=messages.some((message)=>message.senderUserId===selectedUserId&&message.recipientUserId===currentUserId&&!message.readAt);if(!unread)return;void markInboxConversationRead(selectedUserId).then(async()=>{await load();window.dispatchEvent(new Event("tenops:notifications-changed"));}).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to mark messages read."));},[currentUserId,load,messages,open,selectedUserId]);
  useEffect(()=>{if(!selected)return;window.requestAnimationFrame(()=>historyRef.current?.scrollTo({top:historyRef.current.scrollHeight,behavior:"smooth"}));},[selected]);

  async function send(){const target=selectedUserId||recipientId;if(!target||!body.trim()||sending)return;setSending(true);setError("");try{if(files.length)await sendInboxMessageWithAttachments(target,body.trim(),jobId,files);else await sendInboxMessage(target,body.trim(),jobId);resetComposer();setSelectedUserId(target);setNewMessage(false);await load();window.dispatchEvent(new Event("tenops:notifications-changed"));}catch(caught){setError(caught instanceof Error?caught.message:"Unable to send message.");}finally{setSending(false);}}
  if(!open||typeof document==="undefined")return null;const showConversation=Boolean(selected||newMessage);

  return createPortal(<div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/45 p-0 sm:p-4" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}>
    <section role="dialog" aria-modal="true" aria-labelledby="my-work-inbox-title" className="flex h-[100dvh] w-full flex-col overflow-hidden border-slate-300 bg-white pt-[env(safe-area-inset-top)] shadow-2xl sm:h-[min(780px,calc(100dvh-2rem))] sm:max-w-5xl sm:rounded-lg sm:border sm:pt-0">
      <header className="flex shrink-0 items-center justify-between border-b border-slate-200 px-4 py-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-blue-200 bg-blue-50"><Inbox className="h-5 w-5 text-blue-800" /></span><div><h2 id="my-work-inbox-title" className="text-lg font-semibold text-slate-950">Inbox</h2><p className="text-xs text-slate-500">Private conversations</p></div></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close Inbox" className="flex h-10 w-10 items-center justify-center rounded-md border border-red-400 bg-red-50 text-red-700 transition hover:bg-red-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600"><X className="h-5 w-5" /></button></header>
      {error&&<div role="alert" className="shrink-0 border-b border-red-200 bg-red-50 px-4 py-2 text-sm font-medium text-red-800">{error}</div>}
      <div className="grid min-h-0 flex-1 md:grid-cols-[310px_minmax(0,1fr)]">
        <aside className={`${showConversation?"hidden md:flex":"flex"} min-h-0 flex-col border-r border-slate-200 bg-slate-50/60`}><div className="border-b border-slate-200 p-3"><button type="button" onClick={()=>{setNewMessage(true);setSelectedUserId("");setRecipientId("");resetComposer();}} className="tenops-selected-surface flex h-11 w-full items-center justify-center gap-2 rounded-md border px-3 text-sm font-semibold"><MessageSquarePlus className="h-4 w-4" />New message</button></div><div className="min-h-0 flex-1 overflow-y-auto">{conversations.length?conversations.map((conversation)=><button key={conversation.userId} type="button" onClick={()=>chooseConversation(conversation.userId)} className="flex w-full gap-3 border-b border-slate-200 px-3 py-3 text-left hover:bg-white"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border text-xs font-bold ${conversation.isSystem?"tenops-selected-surface":"border-slate-300 bg-white text-slate-700"}`}>{conversation.isSystem?<Sparkles className="h-4 w-4" />:initials(conversation.name)}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm text-slate-950">{conversation.name}</strong><time className="shrink-0 text-[10px] text-slate-400">{conversationTime(conversation.latest.createdAt)}</time></span><span className="mt-0.5 flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-xs text-slate-600">{conversation.latest.body}</span>{conversation.unread?<span className="inline-flex min-w-5 items-center justify-center rounded-full bg-red-600 px-1.5 text-[10px] font-bold text-white">{conversation.unread>9?"9+":conversation.unread}</span>:null}</span></span></button>):<p className="px-5 py-10 text-center text-sm text-slate-500">No conversations yet.<span className="mt-1 block">Start with New message.</span></p>}</div></aside>
        <div className={`${showConversation?"flex":"hidden md:flex"} min-h-0 flex-col`}>
          {!showConversation?<div className="m-auto max-w-sm px-6 text-center text-slate-500"><Inbox className="mx-auto h-8 w-8" /><p className="mt-3 text-sm">Select a recipient to start a conversation.</p></div>:<>
            <div className="flex shrink-0 items-center gap-2 border-b border-slate-200 px-3 py-2"><button type="button" onClick={()=>{setSelectedUserId("");setNewMessage(false);resetComposer();}} className="flex h-11 w-11 items-center justify-center md:hidden" aria-label="Back to conversations"><ArrowLeft className="h-5 w-5" /></button>{!newMessage&&selected?<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-[11px] font-bold ${selected.isSystem?"tenops-selected-surface":"border-slate-300 bg-slate-50"}`}>{selected.isSystem?<Sparkles className="h-4 w-4" />:initials(selected.name)}</span>:null}<div className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-950">{newMessage?"New message":selected?.name}</strong>{!newMessage&&selected?.role?<span className="block text-[10px] uppercase tracking-wide text-slate-400">{selected.role}</span>:null}</div></div>
            {newMessage?<div className="border-b border-slate-200 p-3"><label className="text-xs font-medium text-slate-600">To<select value={recipientId} onChange={(event)=>setRecipientId(event.target.value)} className="mt-1 h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">Choose a TenOps user</option>{collaborators.map((user)=><option key={user.userId} value={user.userId}>{user.displayName}</option>)}</select></label>{!recipientId?<p className="mt-2 text-xs text-slate-500">Select a recipient to start a conversation.</p>:null}</div>:null}
            <div ref={historyRef} className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-slate-50/60 px-3 py-4 sm:px-5">{selected?.messages.map((message,index)=>{const sent=message.senderUserId===currentUserId;const showDay=index===0||dayKey(selected.messages[index-1].createdAt)!==dayKey(message.createdAt);return <div key={message.id}>{showDay?<div className="my-3 flex items-center gap-3"><span className="h-px flex-1 bg-slate-200" /><span className="text-[10px] font-medium uppercase tracking-wide text-slate-400">{dayLabel(message.createdAt)}</span><span className="h-px flex-1 bg-slate-200" /></div>:null}<article className={`mb-3 max-w-[88%] rounded-md border px-3 py-2 ${sent?"ml-auto border-blue-200 bg-blue-50":"border-slate-200 bg-white"}`}><div className="whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-800">{message.body}</div>{message.attachments.map((attachment)=><AttachmentView key={attachment.id} attachment={attachment} onError={setError} onPreview={setPreview} />)}{message.jobId?<button type="button" onClick={()=>openProductionJob(message.jobId)} className="mt-2 inline-flex max-w-full items-center gap-1 text-xs font-medium text-blue-800 hover:underline"><BriefcaseBusiness className="h-3.5 w-3.5 shrink-0" /><span className="truncate">{[message.jobNumber,message.jobName].filter(Boolean).join(" · ")||"Open Job"}</span></button>:null}<time className="mt-1 block text-[10px] text-slate-400">{timeLabel(message.createdAt)}</time></article></div>;})}</div>
            {selected?.isSystem?<div className="shrink-0 border-t border-slate-200 bg-slate-50 px-4 py-3 text-center text-xs font-medium text-slate-500">TenOps system messages are read-only.</div>:<div className="shrink-0 border-t border-slate-200 bg-white px-3 pt-3 pb-[max(.75rem,env(safe-area-inset-bottom))]">
              {files.length?<div className="mb-2 space-y-1">{files.map((file,index)=><div key={`${file.name}-${file.size}-${index}`} className="flex min-w-0 items-center gap-2 rounded border border-slate-200 bg-slate-50 px-2 py-1.5"><Paperclip className="h-3.5 w-3.5 shrink-0" /><span className="min-w-0 flex-1 truncate text-xs">{file.name}</span><span className="shrink-0 text-[10px] text-slate-400">{fileSize(file.size)}</span><button type="button" onClick={()=>setFiles((current)=>current.filter((_,candidate)=>candidate!==index))} aria-label={`Remove ${file.name}`} className="flex h-9 w-9 shrink-0 items-center justify-center text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div>:null}
              {linkedJob?<div className="mb-2 flex items-center gap-2 rounded border border-blue-200 bg-blue-50 px-2 py-1.5"><BriefcaseBusiness className="h-4 w-4 shrink-0 text-blue-800" /><span className="min-w-0 flex-1 truncate text-xs font-medium text-blue-900">{jobLabel(linkedJob)}</span><button type="button" onClick={()=>{setJobPickerOpen(true);setJobQuery("");}} className="h-9 px-2 text-xs font-medium text-blue-800">Change</button><button type="button" onClick={()=>setJobId("")} aria-label="Remove linked Job" className="flex h-9 w-9 items-center justify-center text-slate-500"><X className="h-4 w-4" /></button></div>:null}
              {jobPickerOpen&&!linkedJob?<div className="mb-2 rounded border border-slate-300 bg-white p-2"><p className="mb-2 text-xs text-slate-500">Reference the Job this message is about.</p><input autoFocus value={jobQuery} onChange={(event)=>setJobQuery(event.target.value)} placeholder="Search number or Job name" className="h-10 w-full rounded border border-slate-300 bg-white px-3 text-sm" /><div className="mt-1 max-h-36 overflow-y-auto">{jobMatches.map((job)=><button key={job.id} type="button" onClick={()=>{setJobId(job.id);setJobPickerOpen(false);setJobQuery("");}} className="block min-h-10 w-full truncate px-2 text-left text-xs hover:bg-slate-50">{jobLabel(job)}</button>)}</div><button type="button" onClick={()=>setJobPickerOpen(false)} className="mt-1 h-9 px-2 text-xs font-medium text-slate-600">Cancel</button></div>:null}
              <textarea ref={composeRef} value={body} onChange={(event)=>setBody(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}}} rows={3} placeholder="Write a message…" className="min-h-20 w-full resize-none rounded-md border border-slate-300 bg-white px-3 py-2 text-base sm:text-sm" />
              <div className="mt-2 flex flex-wrap items-center gap-1"><label className="inline-flex h-11 cursor-pointer items-center gap-1.5 rounded px-2 text-xs font-medium text-slate-700 hover:bg-slate-100"><Paperclip className="h-4 w-4" />Attach<input type="file" multiple accept={attachmentAccept} onChange={(event)=>{setFiles((current)=>[...current,...Array.from(event.target.files??[])]);event.currentTarget.value="";}} className="sr-only" /></label>{!linkedJob?<button type="button" onClick={()=>setJobPickerOpen((current)=>!current)} className="inline-flex h-11 items-center gap-1.5 rounded px-2 text-xs font-medium text-slate-700 hover:bg-slate-100"><Link2 className="h-4 w-4" />Link a Job</button>:null}<button type="button" onClick={()=>void send()} disabled={sending||!body.trim()||!(selectedUserId||recipientId)} className="tenops-selected-surface ml-auto flex h-11 items-center gap-2 rounded-md border px-4 text-sm font-semibold disabled:opacity-40"><span>{sending?"Sending…":"Send"}</span><Send className="h-4 w-4" /></button></div>
            </div>}
          </>}
        </div>
      </div>
    </section>
    {preview?.previewUrl?<div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-950/85 p-4" role="dialog" aria-modal="true" aria-label={`Preview ${preview.originalFilename}`} onMouseDown={(event)=>{if(event.target===event.currentTarget)setPreview(null);}}><button type="button" onClick={()=>setPreview(null)} aria-label="Close image preview" className="absolute right-4 top-[max(1rem,env(safe-area-inset-top))] flex h-11 w-11 items-center justify-center rounded bg-white text-slate-900"><X className="h-5 w-5" /></button><Image unoptimized src={preview.previewUrl} alt={preview.originalFilename} width={1600} height={1200} className="max-h-[90dvh] h-auto max-w-full w-auto object-contain" /></div>:null}
  </div>,document.body);
}
