"use client";

import { ArrowLeft, BriefcaseBusiness, FileText, Inbox, MessageSquarePlus, MoreHorizontal, Paperclip, Send, Sparkles, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { createPortal } from "react-dom";
import Image from "next/image";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import { openProductionJob } from "@/modules/production/job-options";
import { createInboxAttachmentUrl, editInboxMessage, isTenOpsSystemInboxUser, loadConversationSummaries, loadInboxUnreadCount, markInboxConversationRead, openInboxAttachment, permanentlyDeleteInboxMessage, sendInboxMessage, type ConversationSummary, type InboxAttachment, type InboxMessage } from "./inbox";
import type { WorkCollaborator } from "./types";
import { canPreview, fileExtension, fileSize } from "./messaging/files";
import { getTransfer, serverTransfer, startTransfer, subscribeTransfer, transferPending } from "./messaging/client";
import { useAttachmentQueue } from "./messaging/useAttachmentQueue";
import InlinePreview from "./messaging/InlinePreview";
import { useConversation } from "./messaging/useConversation";
import TransferPanel from "./messaging/TransferPanel";


const subscribeNoTransfer=()=>()=>{};
const noTransferState=()=>null;
const timeLabel=(value:string)=>new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(value));
const conversationTime=(value:string)=>new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));
const dayLabel=(value:string)=>new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(new Date(value));
const dayKey=(value:string)=>new Date(value).toDateString();
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map((part)=>part[0]?.toUpperCase()).join("")||"?";
function AttachmentView({attachment,onError,onPreview}:{attachment:InboxAttachment;onError:(message:string)=>void;onPreview:(attachment:InboxAttachment)=>void}){
  return <div className="min-w-0">{attachment.preview?<InlinePreview preview={attachment.preview} name={attachment.originalFilename} onOpen={()=>onPreview(attachment)}/>:null}<div className="mt-2 flex max-w-full flex-wrap items-center gap-2 rounded border border-slate-200 bg-white px-2 py-2 text-left"><FileText className="h-4 w-4 shrink-0 text-slate-500"/><span className="min-w-0 flex-1"><bdi className="block truncate text-xs font-medium text-slate-800">{attachment.originalFilename}</bdi><span className="block text-[10px] text-slate-500">{fileExtension(attachment.originalFilename)} · {fileSize(attachment.byteSize)}</span></span>{canPreview(attachment)&&!attachment.preview?<button type="button" onClick={()=>onPreview(attachment)} className="min-h-10 px-2 text-xs text-blue-800">Preview image</button>:null}<button type="button" onClick={()=>void openInboxAttachment(attachment).catch(caught=>onError(caught instanceof Error?caught.message:"Unable to download attachment."))} className="min-h-10 px-2 text-xs text-blue-800">Download</button></div></div>;
}

export default function InboxDialog({open,onClose,currentUserId,collaborators,initialUserId="",startNewMessage=false,onUnreadChange,presentation="dialog"}:{open:boolean;onClose:()=>void;currentUserId:string;collaborators:WorkCollaborator[];initialUserId?:string;startNewMessage?:boolean;onUnreadChange:(count:number)=>void;presentation?:"dialog"|"sidepane"}){
  const auth=useAuth();
  const transfer=useSyncExternalStore(subscribeTransfer,getTransfer,serverTransfer);
  const transferPhaseSnapshot=useCallback(()=>transfer?.state.phase??null,[transfer]);
  const transferPhase=useSyncExternalStore(transfer?.subscribe??subscribeNoTransfer,transferPhaseSnapshot,noTransferState);
  const transferBlocked=transferPending(transfer);
  // A completed banner may survive rerenders, close/reopen, or a new composer mount.
  const handledTransfer=useRef(transfer&&!transferBlocked?transfer:null);
  const[summaries,setSummaries]=useState<ConversationSummary[]>([]);const[selectedUserId,setSelectedUserId]=useState("");const[newMessage,setNewMessage]=useState(false);const[recipientId,setRecipientId]=useState("");
  const[body,setBody]=useState("");
  const[sending,setSending]=useState(false);const[sendStage,setSendStage]=useState("");const[error,setError]=useState("");const[preview,setPreview]=useState<InboxAttachment|null>(null);
  const attachmentQueue=useAttachmentQueue(sending||transferBlocked,setError);
  const {files,clear:clearAttachments}=attachmentQueue;
  const[actionMessageId,setActionMessageId]=useState("");const[editingMessageId,setEditingMessageId]=useState("");const[editBody,setEditBody]=useState("");const[messageActionBusy,setMessageActionBusy]=useState(false);
  const closeRef=useRef<HTMLButtonElement>(null);const composeRef=useRef<HTMLTextAreaElement>(null);const historyRef=useRef<HTMLDivElement>(null);const initialUserHandledRef=useRef("");
  const {messages,setMessages,loading,hasOlder,older,refresh,reconcile}=useConversation(open?selectedUserId:"",setError);
  const nearBottomRef=useRef(true);const scrollPeerRef=useRef("");const scrollLastRef=useRef("");const olderBusyRef=useRef(false);const readKeyRef=useRef("");
  const summaryGeneration=useRef(0);
  const typingChannelRef=useRef<ReturnType<typeof supabase.channel>|null>(null);const typingStopTimerRef=useRef<number|undefined>(undefined);const remoteTypingTimerRef=useRef<number|undefined>(undefined);const lastTypingBroadcastRef=useRef(0);
  const[remoteTypingUserId,setRemoteTypingUserId]=useState("");

  const load=useCallback(async()=>{const generation=++summaryGeneration.current;if(!auth.profile?.isActive)return;try{const [next,count]=await Promise.all([loadConversationSummaries(),loadInboxUnreadCount(currentUserId)]);if(generation!==summaryGeneration.current)return;setSummaries(next);setError(current=>current==="Unable to load Inbox."?"":current);onUnreadChange(count);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load Inbox.");}},[auth.profile?.isActive,currentUserId,onUnreadChange]);
  const summaryTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const queueLoad=useCallback(()=>{clearTimeout(summaryTimer.current);summaryTimer.current=setTimeout(()=>void load(),100);},[load]);
  useEffect(()=>()=>clearTimeout(summaryTimer.current),[]);
  const conversations=useMemo(()=>summaries.map(item=>({...item,isSystem:isTenOpsSystemInboxUser(item.userId)})),[summaries]);
  const summary=conversations.find(item=>item.userId===selectedUserId);
  const selected=selectedUserId?{userId:selectedUserId,name:summary?.name??collaborators.find(user=>user.userId===selectedUserId)?.displayName??"Conversation",role:summary?.role??"",isSystem:isTenOpsSystemInboxUser(selectedUserId),messages}:undefined;
  const typingPeerId=open&&selectedUserId&&!isTenOpsSystemInboxUser(selectedUserId)?selectedUserId:"";
  const resetComposer=useCallback(()=>{setBody("");clearAttachments();},[clearAttachments]);
  const chooseConversation=useCallback((userId:string)=>{if(transferBlocked)return;setSelectedUserId(userId);setNewMessage(false);setRecipientId(userId);resetComposer();},[resetComposer,transferBlocked]);
  const broadcastTyping=useCallback((typing:boolean)=>{const channel=typingChannelRef.current;if(channel)void channel.send({type:"broadcast",event:"typing",payload:{userId:currentUserId,typing}});},[currentUserId]);
  const announceTyping=useCallback((typing:boolean)=>{window.clearTimeout(typingStopTimerRef.current);if(!typing){broadcastTyping(false);lastTypingBroadcastRef.current=0;return;}const now=Date.now();if(now-lastTypingBroadcastRef.current>=1000){broadcastTyping(true);lastTypingBroadcastRef.current=now;}typingStopTimerRef.current=window.setTimeout(()=>{broadcastTyping(false);lastTypingBroadcastRef.current=0;},1300);},[broadcastTyping]);

  useEffect(()=>{if(!open)return;void load();closeRef.current?.focus();const changed=queueLoad;window.addEventListener("tenops:messaging-changed",changed);return()=>{
    // Counter invalidates asynchronous summary reads after close/unmount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    summaryGeneration.current++;window.removeEventListener("tenops:messaging-changed",changed);};},[load,open,queueLoad]);
  useEffect(()=>{if(!open){initialUserHandledRef.current="";return;}if(initialUserId&&initialUserHandledRef.current!==initialUserId){initialUserHandledRef.current=initialUserId;chooseConversation(initialUserId);}},[chooseConversation,initialUserId,open]);
  useEffect(()=>{if(!open||!startNewMessage)return;setNewMessage(true);setSelectedUserId("");setRecipientId("");resetComposer();},[open,resetComposer,startNewMessage]);
  useEffect(()=>{if(!open||!isTenOpsSystemInboxUser(selectedUserId))return;const channel=supabase.channel(`my-work-system:${currentUserId}`).on("postgres_changes",{event:"*",schema:"public",table:"my_work_messages",filter:`recipient_user_id=eq.${currentUserId}`},event=>{const row=event.new as {id?:string;sender_user_id?:string};if(row.id&&!row.sender_user_id)reconcile(row.id);}).subscribe(status=>{if(status==="SUBSCRIBED")void refresh();});return()=>{void supabase.removeChannel(channel);};},[currentUserId,open,selectedUserId,reconcile,refresh]);
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(preview)setPreview(null);else onClose();};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[onClose,open,preview]);
  useEffect(()=>{if(newMessage)composeRef.current?.focus();},[newMessage]);
  useEffect(()=>{if(!typingPeerId||!currentUserId)return;let active=true;let channel:ReturnType<typeof supabase.channel>|null=null;const subscribe=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!active||!session?.access_token)return;await supabase.realtime.setAuth(session.access_token);if(!active)return;const topic=[currentUserId,typingPeerId].sort().join(":");channel=supabase.channel(`my-work-typing:${topic}`,{config:{private:true,broadcast:{self:false}}}).on("broadcast",{event:"typing"},({payload})=>{if(payload?.userId!==typingPeerId)return;window.clearTimeout(remoteTypingTimerRef.current);if(payload.typing!==true){setRemoteTypingUserId("");return;}setRemoteTypingUserId(typingPeerId);remoteTypingTimerRef.current=window.setTimeout(()=>setRemoteTypingUserId(""),2600);});channel.on("broadcast",{event:"message_changed"},({payload})=>{if(typeof payload?.id==="string"){reconcile(payload.id,payload.kind!=="new");queueLoad();}});typingChannelRef.current=channel;channel.subscribe(status=>{if(status==="SUBSCRIBED")void refresh();});};void subscribe();return()=>{active=false;if(channel)void channel.send({type:"broadcast",event:"typing",payload:{userId:currentUserId,typing:false}});typingChannelRef.current=null;window.clearTimeout(typingStopTimerRef.current);window.clearTimeout(remoteTypingTimerRef.current);lastTypingBroadcastRef.current=0;setRemoteTypingUserId("");if(channel)void supabase.removeChannel(channel);};},[currentUserId,typingPeerId,reconcile,refresh,queueLoad]);

  useEffect(()=>{if(!open||!selectedUserId)return;const unread=messages.filter(message=>message.senderUserId===selectedUserId&&message.recipientUserId===currentUserId&&!message.readAt);const key=selectedUserId+":"+unread.map(message=>message.id).join(",");if(!unread.length||key===readKeyRef.current)return;readKeyRef.current=key;const peer=selectedUserId;const ids=new Set(unread.map(message=>message.id));void markInboxConversationRead(peer).then(()=>{setMessages(current=>current.map(message=>message.senderUserId===peer&&ids.has(message.id)&&!message.readAt?{...message,readAt:new Date().toISOString()}:message));void load();window.dispatchEvent(new Event("tenops:notifications-changed"));}).catch(caught=>setError(caught instanceof Error?caught.message:"Unable to mark messages read."));},[currentUserId,messages,load,open,selectedUserId,setMessages]);
  useEffect(()=>{if(!open){scrollPeerRef.current="";scrollLastRef.current="";nearBottomRef.current=true;}},[open]);
  const lastMessageId=messages.at(-1)?.id??"";
  useEffect(()=>{const scroller=historyRef.current;if(!scroller||!lastMessageId)return;const newPeer=scrollPeerRef.current!==selectedUserId;if(newPeer||(scrollLastRef.current!==lastMessageId&&nearBottomRef.current)){scroller.scrollTop=scroller.scrollHeight;nearBottomRef.current=true;}scrollPeerRef.current=selectedUserId;scrollLastRef.current=lastMessageId;},[lastMessageId,selectedUserId]);
  async function loadOlder(){const el=historyRef.current;if(!el||olderBusyRef.current||!hasOlder||loading)return;olderBusyRef.current=true;const peer=selectedUserId;const height=el.scrollHeight;const top=el.scrollTop;try{await older();requestAnimationFrame(()=>{if(historyRef.current===el&&scrollPeerRef.current===peer)el.scrollTop=top+el.scrollHeight-height;});}finally{olderBusyRef.current=false;}}


  useEffect(()=>{
    if(!transfer||transferBlocked||handledTransfer.current===transfer)return;
    handledTransfer.current=transfer;
    clearAttachments();
    if(transferPhase==='sent'){
      setSelectedUserId(transfer.draft.recipient);setNewMessage(false);reconcile(transfer.draft.id);
      nearBottomRef.current=true;setBody("");void load();
      window.dispatchEvent(new Event("tenops:notifications-changed"));
    }
    // Cancellation preserves unsent text; both terminal outcomes release the queue.
    if(open)composeRef.current?.focus();
  },[transfer,transferPhase,transferBlocked,clearAttachments,reconcile,load,open]);
  async function send(){const target=selectedUserId||recipientId;if(!target||(!body.trim()&&!files.length)||sending||transferBlocked)return;announceTyping(false);setError("");
    if(files.length){try{startTransfer(currentUserId,target,body.trim(),"",files);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to start transfer.");}return;}
    setSending(true);try{const id=await sendInboxMessage(target,body.trim());nearBottomRef.current=true;reconcile(id);resetComposer();setSelectedUserId(target);setNewMessage(false);await load();window.dispatchEvent(new Event("tenops:notifications-changed"));}catch(caught){setError(caught instanceof Error?caught.message:"Unable to send message.");}finally{setSending(false);}
  }
  async function previewAttachment(attachment:InboxAttachment){try{setSendStage("Loading preview…");if(!canPreview(attachment))return;const url=await createInboxAttachmentUrl(attachment);setPreview({...attachment,previewUrl:url});}catch(caught){setError(caught instanceof Error?caught.message:"Unable to preview attachment.");}finally{setSendStage("");}}
  async function saveMessageEdit(){if(!editingMessageId||!editBody.trim()||messageActionBusy)return;setMessageActionBusy(true);setError("");try{await editInboxMessage(editingMessageId,editBody);reconcile(editingMessageId);setEditingMessageId("");setEditBody("");setActionMessageId("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to edit message.");}finally{setMessageActionBusy(false);}}
  async function permanentlyDeleteMessage(message:InboxMessage){if(messageActionBusy||!window.confirm("Permanently delete this message? This removes the selected message and its attachments for both participants. This cannot be undone."))return;setMessageActionBusy(true);setError("");try{await permanentlyDeleteInboxMessage(message.id);reconcile(message.id);setActionMessageId("");if(editingMessageId===message.id){setEditingMessageId("");setEditBody("");}await load();window.dispatchEvent(new Event("tenops:notifications-changed"));}catch(caught){setError(caught instanceof Error?caught.message:"Unable to permanently delete message.");}finally{setMessageActionBusy(false);}}
  if(!open||typeof document==="undefined")return null;const showConversation=Boolean(selected||newMessage);

  const sidepane=presentation==="sidepane";
  return createPortal(<div data-global-message-sidebar={sidepane?"":undefined} data-expanded={sidepane?"true":undefined} className={`fixed inset-0 z-[120] flex bg-slate-950/45 p-0 ${sidepane?"items-stretch justify-start":"items-center justify-center sm:p-4"}`} onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}>
    <section role="dialog" aria-modal="true" aria-labelledby="my-work-inbox-title" className={`flex w-full flex-col overflow-hidden border-slate-300 bg-white shadow-2xl ${sidepane?"h-full border-r md:max-w-5xl xl:max-w-[min(72rem,72vw)]":"h-[100dvh] pt-[env(safe-area-inset-top)] sm:h-[min(780px,calc(100dvh-2rem))] sm:max-w-5xl sm:rounded-lg sm:border sm:pt-0"}`}>
      <header className="flex shrink-0 items-center justify-between border-b border-slate-200 px-4 py-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-blue-200 bg-blue-50"><Inbox className="h-5 w-5 text-blue-800" /></span><div><h2 id="my-work-inbox-title" className="text-lg font-semibold text-slate-950">Inbox</h2><p className="text-xs text-slate-500">Private conversations</p></div></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close Inbox" className="flex h-10 w-10 items-center justify-center rounded-md border border-red-400 bg-red-50 text-red-700 transition hover:bg-red-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-600"><X className="h-5 w-5" /></button></header>
      {transfer?<TransferPanel key={transfer.draft.id} transfer={transfer}/>:null}
      {error&&<div role="alert" className="shrink-0 border-b border-red-200 bg-red-50 px-4 py-2 text-sm font-medium text-red-800">{error}</div>}
      <div className="grid min-h-0 flex-1 md:grid-cols-[310px_minmax(0,1fr)]">
        <aside className={`${showConversation?"hidden md:flex":"flex"} min-h-0 flex-col border-r border-slate-200 bg-slate-50/60`}><div className="border-b border-slate-200 p-3"><button type="button" disabled={transferBlocked} onClick={()=>{setNewMessage(true);setSelectedUserId("");setRecipientId("");resetComposer();}} className="tenops-selected-surface flex h-11 w-full items-center justify-center gap-2 rounded-md border px-3 text-sm font-semibold"><MessageSquarePlus className="h-4 w-4" />New message</button></div><div className="min-h-0 flex-1 overflow-y-auto">{loading&&!conversations.length?<p className="px-5 py-8 text-center text-sm text-slate-500">Loading conversations…</p>:conversations.length?conversations.map((conversation)=><button key={conversation.userId} type="button" onClick={()=>chooseConversation(conversation.userId)} className="flex w-full gap-3 border-b border-slate-200 px-3 py-3 text-left hover:bg-white"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border text-xs font-bold ${conversation.isSystem?"tenops-selected-surface":"border-slate-300 bg-white text-slate-700"}`}>{conversation.isSystem?<Sparkles className="h-4 w-4" />:initials(conversation.name)}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm text-slate-950">{conversation.name}</strong><time className="shrink-0 text-[10px] text-slate-400">{conversationTime(conversation.latest.createdAt)}</time></span><span className="mt-0.5 flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-xs text-slate-600">{conversation.latest.body}</span>{conversation.unread?<span className="inline-flex min-w-5 items-center justify-center rounded-full bg-red-600 px-1.5 text-[10px] font-bold text-white">{conversation.unread>9?"9+":conversation.unread}</span>:null}</span></span></button>):<p className="px-5 py-10 text-center text-sm text-slate-500">No conversations yet.<span className="mt-1 block">Start with New message.</span></p>}</div></aside>
        <div className={`${showConversation?"flex":"hidden md:flex"} min-h-0 flex-col`}>
          {!showConversation?<div className="m-auto max-w-sm px-6 text-center text-slate-500"><Inbox className="mx-auto h-8 w-8" /><p className="mt-3 text-sm">Select a recipient to start a conversation.</p></div>:<>
            <div className="flex shrink-0 items-center gap-2 border-b border-slate-200 px-3 py-2"><button type="button" disabled={transferBlocked} onClick={()=>{setSelectedUserId("");setNewMessage(false);resetComposer();}} className="flex h-11 w-11 items-center justify-center md:hidden" aria-label="Back to conversations"><ArrowLeft className="h-5 w-5" /></button>{!newMessage&&selected?<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-[11px] font-bold ${selected.isSystem?"tenops-selected-surface":"border-slate-300 bg-slate-50"}`}>{selected.isSystem?<Sparkles className="h-4 w-4" />:initials(selected.name)}</span>:null}<div className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-950">{newMessage?"New message":selected?.name}</strong>{!newMessage&&selected?.role?<span className="block text-[10px] uppercase tracking-wide text-slate-400">{selected.role}</span>:null}</div></div>
            {newMessage?<div className="border-b border-slate-200 p-3"><label className="text-xs font-medium text-slate-600">To<select disabled={transferBlocked} value={recipientId} onChange={(event)=>setRecipientId(event.target.value)} className="mt-1 h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm"><option value="">Choose a TenOps user</option>{collaborators.map((user)=><option key={user.userId} value={user.userId}>{user.displayName}</option>)}</select></label>{!recipientId?<p className="mt-2 text-xs text-slate-500">Select a recipient to start a conversation.</p>:null}</div>:null}
            <div ref={historyRef} data-message-history onScroll={event=>{const el=event.currentTarget;nearBottomRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<100;if(el.scrollTop<80)void loadOlder();}} className={`${selected?.messages.length?"min-h-0 flex-1 overflow-y-auto py-4":"shrink-0 py-1"} overscroll-contain bg-slate-50/60 px-3 sm:px-5`}>{hasOlder?<button type="button" disabled={loading} onClick={()=>void loadOlder()} className="mx-auto block min-h-10 px-3 text-xs text-blue-800">{loading?"Loading…":"Older messages"}</button>:null}{selected?.messages.map((message,index)=>{
              const sent=message.senderUserId===currentUserId;const showDay=index===0||dayKey(selected.messages[index-1].createdAt)!==dayKey(message.createdAt);const isSystem=isTenOpsSystemInboxUser(message.senderUserId);const canEdit=sent&&!isSystem;const canDelete=auth.profile?.role==="admin"&&!isSystem;const editing=editingMessageId===message.id;
              return <div key={message.id}>{showDay?<div className="my-3 flex items-center gap-3"><span className="h-px flex-1 bg-slate-200" /><span className="text-[10px] font-medium uppercase tracking-wide text-slate-400">{dayLabel(message.createdAt)}</span><span className="h-px flex-1 bg-slate-200" /></div>:null}<article className={`relative mb-3 max-w-[88%] rounded-md border px-3 py-2 ${sent?"ml-auto border-blue-200 bg-blue-50":"border-slate-200 bg-white"}`}>
                {(canEdit||canDelete)&&!editing?<div className="absolute right-1 top-1"><button type="button" onClick={()=>setActionMessageId((current)=>current===message.id?"":message.id)} aria-label="Message actions" aria-expanded={actionMessageId===message.id} className="flex h-10 w-10 items-center justify-center rounded text-slate-500 hover:bg-slate-100"><MoreHorizontal className="h-4 w-4" /></button>{actionMessageId===message.id?<div className="absolute right-0 z-20 mt-1 min-w-52 rounded-md border border-slate-300 bg-white p-1 shadow-lg">{canEdit?<button type="button" onClick={()=>{setEditingMessageId(message.id);setEditBody(message.body);setActionMessageId("");}} className="block min-h-10 w-full rounded px-3 text-left text-sm hover:bg-slate-50">Edit message</button>:null}{canDelete?<button type="button" onClick={()=>void permanentlyDeleteMessage(message)} className="block min-h-10 w-full rounded px-3 text-left text-sm font-medium text-red-700 hover:bg-red-50">Permanently delete message</button>:null}</div>:null}</div>:null}
                {editing?<div className="space-y-2 pr-1"><textarea autoFocus value={editBody} onChange={(event)=>setEditBody(event.target.value)} rows={4} className="w-full resize-y rounded-md border border-slate-300 bg-white px-3 py-2 text-base sm:text-sm" /><div className="flex flex-wrap justify-end gap-2"><button type="button" disabled={messageActionBusy} onClick={()=>{setEditingMessageId("");setEditBody("");}} className="h-10 rounded-md border border-slate-300 px-3 text-sm font-medium">Cancel</button><button type="button" disabled={messageActionBusy||!editBody.trim()} onClick={()=>void saveMessageEdit()} className="tenops-selected-surface h-10 rounded-md border px-3 text-sm font-medium disabled:opacity-40">{messageActionBusy?"Saving…":"Save"}</button></div></div>:<div className={`${canEdit||canDelete?"pr-8":""} whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-800`}>{message.body}</div>}
                {!editing?<div className={message.attachments.length>1?"grid grid-cols-2 gap-2":""}>{message.attachments.map((attachment)=><div key={attachment.id} className={attachment.preview?"min-w-0":"col-span-2 min-w-0"}><AttachmentView attachment={attachment} onError={setError} onPreview={(item)=>void previewAttachment(item)} /></div>)}</div>:null}
                {!editing&&message.jobId?<button type="button" onClick={()=>openProductionJob(message.jobId)} className="mt-2 inline-flex max-w-full items-center gap-1 text-xs font-medium text-blue-800 hover:underline"><BriefcaseBusiness className="h-3.5 w-3.5 shrink-0" /><span className="truncate">{[message.jobNumber,message.jobName].filter(Boolean).join(" · ")||"Open Job"}</span></button>:null}
                {!editing?<div className="mt-1 flex items-center gap-1.5 text-[10px] text-slate-400"><time>{timeLabel(message.createdAt)}</time>{message.editedAt?<span>· Edited</span>:null}</div>:null}
              </article></div>;
            })}</div>
            {selected?.isSystem?<div className="shrink-0 border-t border-slate-200 bg-slate-50 px-4 py-3 text-center text-xs font-medium text-slate-500">TenOps system messages are read-only.</div>:<div {...attachmentQueue.events} data-messaging-composer className={`shrink-0 border-t border-slate-200 px-3 pt-3 pb-[max(.75rem,env(safe-area-inset-bottom))] ${attachmentQueue.dragging?"bg-blue-50 ring-2 ring-inset ring-blue-500":"bg-white"}`}>
              {attachmentQueue.dragging?<p role="status" className="text-xs text-blue-800">Drop files to attach</p>:null}
              {files.length?<div className="mb-2 max-h-40 space-y-1 overflow-y-auto">{files.map((file,index)=><div key={`${file.name}-${file.size}-${index}`} className="flex min-w-0 items-center gap-2 rounded border border-slate-200 bg-slate-50 px-2 py-1.5"><Paperclip className="h-3.5 w-3.5 shrink-0" /><bdi className="min-w-0 flex-1 truncate text-xs">{file.name}</bdi><span className="shrink-0 text-[10px] text-slate-400">{fileSize(file.size)}</span><button type="button" disabled={transferBlocked} onClick={()=>attachmentQueue.remove(index)} aria-label={`Remove ${file.name}`} className="flex h-9 w-9 shrink-0 items-center justify-center text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div>:null}
              <div aria-live="polite" className="h-5 px-1 text-[11px] italic text-slate-500">{remoteTypingUserId===typingPeerId&&selected?`${selected.name} is typing…`:null}</div><textarea disabled={transferBlocked} ref={composeRef} value={body} onChange={(event)=>{setBody(event.target.value);announceTyping(Boolean(event.target.value));}} onBlur={()=>announceTyping(false)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}}} rows={3} aria-label="Message" aria-describedby="messaging-attachment-help" placeholder="Write a message…" className="min-h-20 w-full resize-none rounded-md border border-slate-300 bg-white px-3 py-2 text-base sm:text-sm" />
              <p id="messaging-attachment-help" className="mt-1 text-[10px] text-slate-500">Attach, paste images/files, or drop files here. 50 MB per file · 200 MB per message. Clipboard support varies by browser.</p>{sendStage?<p role="status" className="mt-2 text-xs font-medium text-blue-800">{sendStage}</p>:null}<div className="mt-2 flex flex-wrap items-center gap-1"><label className="inline-flex h-11 cursor-pointer items-center gap-1.5 rounded px-2 text-xs font-medium text-slate-700 hover:bg-slate-100 focus-within:ring-2 focus-within:ring-blue-500"><Paperclip className="h-4 w-4" />Attach<input aria-label="Attach files" type="file" multiple disabled={sending||transferBlocked} className="sr-only" onChange={event=>{const selected=Array.from(event.currentTarget.files??[]);event.currentTarget.value="";attachmentQueue.add(selected,"picker",event.nativeEvent);}}/></label><button type="button" onClick={()=>void send()} disabled={sending||transferBlocked||(!body.trim()&&!files.length)||!(selectedUserId||recipientId)} className="tenops-selected-surface ml-auto flex h-11 items-center gap-2 rounded-md border px-4 text-sm font-semibold disabled:opacity-40"><span>{sending?sendStage||"Sending…":"Send"}</span><Send className="h-4 w-4" /></button></div>
            </div>}
          </>}
        </div>
      </div>
    </section>
    {preview?.previewUrl?<div className="fixed inset-0 z-[130] flex items-center justify-center bg-slate-950/85 p-4" role="dialog" aria-modal="true" aria-label={`Preview ${preview.originalFilename}`} onMouseDown={(event)=>{if(event.target===event.currentTarget)setPreview(null);}}><button type="button" onClick={()=>setPreview(null)} aria-label="Close image preview" className="absolute right-4 top-[max(1rem,env(safe-area-inset-top))] flex h-11 w-11 items-center justify-center rounded bg-white text-slate-900"><X className="h-5 w-5" /></button><Image onError={()=>{setPreview(null);setError("Preview unavailable. Use Download to save the attachment.");}} unoptimized src={preview.previewUrl} alt={preview.originalFilename} width={1600} height={1200} className="max-h-[90dvh] h-auto max-w-full w-auto object-contain" /></div>:null}
  </div>,document.body);
}
