import { extractEmbeddedPdfText } from '@/modules/production/providers/pdf-text';
import type { DrawingFieldEvidence, DrawingSuggestionKey, DrawingSuggestions } from './types';
const KNOWN_LABELS=/^(?:PROJECT|LOCATION|PROJECT\s*#|CUSTOMER|ITEM|REF|DWG\.\s*DATE|REV\.\s*#\s*\/\s*DATE|TERR\.\s*COLOR\s*PLATE|MATRIX|FINISH|QTY\s*REQ|PROD\s*WO\s*#|NOTE)\s*:?$/i;
const normalizedLines=(text:string)=>text.replace(/\r/g,'').split('\n').map((line)=>line.trim()).filter(Boolean);
function exactLabeledValue(lines:string[],label:RegExp){const indexes=lines.map((line,index)=>label.test(line.replace(/:$/,''))?index:-1).filter((index)=>index>=0);if(indexes.length!==1)return'';const value=lines[indexes[0]+1]??'';if(!value||KNOWN_LABELS.test(value)||value.length>160)return'';return value;}
const evidence=(value:string,sourceFile:string,sourceLabel:string):DrawingFieldEvidence|undefined=>value?{value,sourceFile,jobAttachmentId:'',sourceLabel,confidence:'exact-label'}:undefined;
const matching=(value:string,pattern:RegExp)=>pattern.test(value)?value:'';
export function extractDrawingSuggestionsFromText(text:string,sourceFile='drawing.pdf'):DrawingSuggestions{
  const lines=normalizedLines(text);const quantityValue=exactLabeledValue(lines,/^QTY\s*REQ$/i);const quantityMatch=quantityValue.match(/^(\d+(?:\.\d+)?)\s+(each|ea|lot|pcs?)$/i);
  const raw:Partial<Record<DrawingSuggestionKey,DrawingFieldEvidence|undefined>>={projectName:evidence(matching(exactLabeledValue(lines,/^PROJECT$/i),/[A-Za-z]{2}/),sourceFile,'PROJECT'),projectLocation:evidence(matching(exactLabeledValue(lines,/^LOCATION$/i),/[A-Za-z]{2}/),sourceFile,'LOCATION'),projectNumber:evidence(matching(exactLabeledValue(lines,/^PROJECT\s*#$/i),/^\d{2}-\d{4}$/),sourceFile,'PROJECT #'),customer:evidence(matching(exactLabeledValue(lines,/^CUSTOMER$/i),/[A-Za-z]{2}/),sourceFile,'CUSTOMER'),item:evidence(matching(exactLabeledValue(lines,/^ITEM$/i),/[A-Za-z]{2}/),sourceFile,'ITEM'),ref:evidence(matching(exactLabeledValue(lines,/^REF$/i),/[A-Za-z]{2}/),sourceFile,'REF'),colorPlate:evidence(matching(exactLabeledValue(lines,/^TERR\.\s*COLOR\s*PLATE$/i),/^[A-Z]\d{2}-[A-Z0-9-]+$/i),sourceFile,'TERR. COLOR PLATE'),matrix:evidence(matching(exactLabeledValue(lines,/^MATRIX$/i),/[A-Za-z]{2}/),sourceFile,'MATRIX'),finish:evidence(matching(exactLabeledValue(lines,/^FINISH$/i),/^\d+\s*g\.?$/i),sourceFile,'FINISH'),quantity:evidence(quantityMatch?.[1]??'',sourceFile,'QTY REQ'),unit:evidence(quantityMatch?.[2]?.toUpperCase()??'',sourceFile,'QTY REQ')};
  raw.description=evidence(raw.item?.value??'',sourceFile,'ITEM');
  return{fields:Object.fromEntries(Object.entries(raw).filter((entry):entry is [string,DrawingFieldEvidence]=>Boolean(entry[1]))),sourceFile};
}
export async function extractDrawingSuggestions(file:File){return extractDrawingSuggestionsFromText(await extractEmbeddedPdfText(file),file.name);}
export function drawingSuggestionConflicts(suggestions:DrawingSuggestions[]){const byField=new Map<string,DrawingFieldEvidence[]>();for(const suggestion of suggestions)for(const[key,entry]of Object.entries(suggestion.fields)){const values=byField.get(key)??[];values.push(entry);byField.set(key,values);}const conflicts:string[]=[];for(const[field,entries]of byField){const distinct=new Map(entries.map((entry)=>[entry.value.trim().toLocaleLowerCase(),entry]));if(distinct.size>1)conflicts.push(`${field}: ${[...distinct.values()].map((entry)=>`${entry.sourceFile} says “${entry.value}”`).join('; ')}.`);}return conflicts;}
