import type { ProposalEstimateAssumptions, ProposalEstimateInputs } from './estimate-types';

export const PROPOSAL_ESTIMATE_CALCULATION_VERSION = 'proposal-estimate-v2' as const;

export const proposalEstimateDefaultAssumptions: ProposalEstimateAssumptions = {
  materialDensityLbPerCubicFoot: 140,
  batchCapacityCubicFeet: 1.768261,
  poundsPerBatch: 200,
  chipBagWeightPounds: 50,
  piecesPerSlab: 2,
  laborRatePerHour: 50,
  crewSize: 6,
  hoursPerDay: 11,
  shopCostPerDay: 1250,
  materialsMarkupPercent: 40,
  freightMarkupPercent: 40,
  laborMarkupPercent: 40,
  shopMarkupPercent: 40,
  repFeePercent: 5,
  difficultyFactorPercent: 0,
  batchRounding: 'fractional',
  shopDayRounding: 'fractional',
  resinGallonsPerBatch: 5,
  resinCostPerGallon: 30,
  hardenerResinRatio: 5,
  hardenerCostPerGallon: 28.5,
  fillerBagsPerBatch: 1,
  fillerCostPerBag: 15,
  groutCoverageSfPerGallon: 1200,
  groutCostPerGallon: 30,
  sealerCoverageSfPerGallon: 250,
  sealerCostPerGallon: 32.7,
  chipFreightPerBag: 7,
  liquidFreightPerGallon: 7,
  fillerFreightPerBag: 7,
  sealerFreightPerGallon: 4,
  blendHoursPerTwentyBags: 1,
  setupHoursPerSlab: 0.5,
  pourHoursPerBatch: 1.25,
  removeStageHoursPerSlab: 0.25,
  gaugeSfPerHour: 95.48611111111111,
  grindSfPerHour: 47.74305555555556,
  groutSfPerHour: 382,
  removeGroutSfPerHour: 95.49,
  sawCutLfPerHour: 114.58,
  edgeFinishLfPerHour: 20,
  handlingItemsPerHour: 44,
  cleanSealSfPerHour: 176,
};

export const emptyProposalEstimateInputs = (): ProposalEstimateInputs => ({
  geometryProfile: 'flat',
  customerQuantity: null,
  lengthInches: null,
  widthInches: null,
  riserHeightInches: null,
  thicknessInches: null,
  depthInches: null,
  roughLengthInches: null,
  roughWidthInches: null,
  roughThicknessInches: null,
  productionQuantityOverride: null,
  finish: '',
  sealer: '',
  resinColor: '',
  filler: '',
  colorPlate: '',
  chipBlend: [],
});
