import type { Proposal,ProposalLine } from './types';
export const proposalEscalationNotice='This estimate may be subject to an escalation if not supplied by requested date';
export const proposalLeadTimeNotice='Lead time for materials and fabrication durations TBD upon receipt of notice to proceed';
const amount=(value:string)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:0;};
export const lineTotal=(line:Pick<ProposalLine,'quantity'|'rate'|'lineType'>)=>line.lineType==='included'||line.lineType==='informational'?0:Math.round(amount(line.quantity)*amount(line.rate)*100)/100;
export function proposalTotals(lines:ProposalLine[],taxEnabled:boolean,taxRate:string){const subtotal=Math.round(lines.reduce((sum,line)=>sum+lineTotal(line),0)*100)/100;const tax=taxEnabled?Math.round(subtotal*amount(taxRate))/100:0;return{subtotal,tax,total:Math.round((subtotal+tax)*100)/100};}
export function proposalTaxClarification(taxEnabled:boolean,county:string,rate:string){const label=county.trim(),rawRate=rate.trim();if(!taxEnabled||!label||!rawRate)return'';const parsed=Number(rawRate);if(!Number.isFinite(parsed))return'';const display=parsed.toLocaleString('en-US',{maximumFractionDigits:3});return`${label} Sales Tax of ${display}% has been added to the estimate. Please note that a Sales Tax-Exempt Certificate will be required in lieu of the sales tax amount listed.`;}
export function knownProposalTaxRate(county:string){return county.trim().toLocaleLowerCase()==='dallas county'?'8.25':'';}
export function proposalClarifications(value:Pick<Proposal,'taxEnabled'|'taxCounty'|'taxRate'|'destinationZip'|'freightEstimate'>){const bullets=['Preliminary shop drawings attached.'];const tax=proposalTaxClarification(value.taxEnabled,value.taxCounty,value.taxRate);if(tax)bullets.push(tax);bullets.push('Crating is included in this quote and listed as a separate additional charge line item.','Shop fabrication cut tickets and color plate samples are included in this quote and listed as a no additional charge line item. Site field dimensioning is NOT included.');const freight=Number(value.freightEstimate);if(value.destinationZip.trim()&&value.freightEstimate.trim()&&Number.isFinite(freight))bullets.push(`Based on the finished product weight, quantity of anticipated crates and destination to Zip Code ${value.destinationZip.trim()} for the items listed on the attached quote, a rough estimate for freight would be about ${formatMoney(freight)} as of today's date.`);return`PLEASE NOTE:\n\n${bullets.map((bullet)=>`- ${bullet}`).join('\n\n')}`;}
const standardCommercialLine=(lineType:ProposalLine['lineType'],description:string,quantity:string,unit:string,order:number):ProposalLine=>({id:crypto.randomUUID(),lineType,itemNumber:'',description,ref:'',colorPlate:'',quantity,unit,length:'',width:'',heightThickness:'',cft:'',lf:'',estimatedWeight:'',rate:'',total:'0',sourceMetadata:{standardCommercialLine:true},displayOrder:order});
export function initializeNewProposalDefaults(value:Proposal){const productLines=value.lines.map((line,index)=>line.lineType==='product'?{...line,quantity:'',unit:'ea.',displayOrder:index}:line);const order=productLines.length;const lines=[...productLines,standardCommercialLine('charge','ESTIMATED Crating for LTL Shipment','1','lot',order),standardCommercialLine('informational','Freight arrangements and cost by customer','','',order+1),standardCommercialLine('included','Shop fabrication tickets & color plate samples','1','ea.',order+2)];const next={...value,taxCounty:'Dallas County',taxRate:'8.25',destinationZip:'',freightEstimate:'',lines};return{...next,notes:value.notes.trim()?value.notes:proposalClarifications(next)};}
export const formatMoney=(value:string|number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
export function nextEstimateVersion(estimateNumber:string){const match=estimateNumber.match(/^(.*)-(\d+)\.(\d+)$/);if(!match)throw new Error('Estimate number does not contain a supported version.');return`${match[1]}-${match[2]}.${Number(match[3])+1}`;}
