import { supabase } from '@/lib/supabase';
import type { Proposal,ProposalLine } from './types';
const line=(row:Record<string,unknown>):ProposalLine=>({id:String(row.id),lineType:String(row.line_type) as ProposalLine['lineType'],itemNumber:String(row.item_number??''),description:String(row.description??''),ref:String(row.ref??''),colorPlate:String(row.color_plate??''),quantity:row.quantity==null?'':String(row.quantity),unit:String(row.unit??''),length:String(row.length??''),width:String(row.width??''),heightThickness:String(row.height_thickness??''),cft:String(row.cft??''),lf:String(row.lf??''),estimatedWeight:String(row.estimated_weight??''),rate:row.rate==null?'':String(row.rate),total:String(row.total??0),sourceMetadata:(row.source_metadata??{}) as Record<string,unknown>,displayOrder:Number(row.display_order??0)});
const proposal=(row:Record<string,unknown>,lines:ProposalLine[]=[]):Proposal=>({id:String(row.id),jobId:row.job_id==null?null:String(row.job_id),lineageId:String(row.lineage_id),priorProposalId:String(row.prior_proposal_id??''),estimateBase:String(row.estimate_base),versionMajor:Number(row.version_major),versionMinor:Number(row.version_minor),estimateNumber:String(row.estimate_number),status:String(row.status) as Proposal['status'],proposalDate:String(row.proposal_date),customerName:String(row.customer_name??''),customerAddress:String(row.customer_address??''),customerContact:String(row.customer_contact??''),projectName:String(row.project_name??''),projectNumber:String(row.project_number??''),projectLocation:String(row.project_location??''),sideMark:String(row.side_mark??''),salesRep:String(row.sales_rep??''),terms:String(row.terms??''),validDays:String(row.valid_days??30),requestedDelivery:String(row.requested_delivery??''),fob:String(row.fob??''),destinationZip:String(row.destination_zip??''),taxCounty:String(row.tax_county??''),freightEstimate:row.freight_estimate==null?'':String(row.freight_estimate),preliminaryDrawingsAttached:Boolean(row.preliminary_drawings_attached),cratingIncluded:Boolean(row.crating_included),cutTicketsIncluded:Boolean(row.cut_tickets_included),fieldDimensioningExcluded:Boolean(row.field_dimensioning_excluded),submittedByName:String(row.submitted_by_name??''),submittedByPhone:String(row.submitted_by_phone??''),submittedByEmail:String(row.submitted_by_email??''),notes:String(row.notes??''),disclaimerSnapshot:String(row.disclaimer_snapshot??''),formulaSnapshot:String(row.formula_snapshot??''),fieldSources:(row.proposal_field_sources??{}) as Proposal['fieldSources'],taxEnabled:Boolean(row.tax_enabled),taxRate:row.tax_rate==null?'':String(row.tax_rate),subtotal:String(row.subtotal??0),tax:String(row.tax??0),total:String(row.total??0),createdAt:String(row.created_at??''),updatedAt:String(row.updated_at??''),issuedAt:String(row.issued_at??''),creatorName:String(row.created_by_name??''),lines});
export async function hasProposalAccess(){const{data,error}=await supabase.rpc('has_proposal_access');if(error)return false;return data===true;}
export async function loadJobProposals(jobId:string){const{data,error}=await supabase.from('proposals').select('*').eq('job_id',jobId).order('version_major',{ascending:false}).order('version_minor',{ascending:false});if(error)throw error;return(data??[]).map((row)=>proposal(row));}
export async function loadProposals(){const{data,error}=await supabase.from('proposals').select('*').order('created_at',{ascending:false});if(error)throw error;return(data??[]).map((row)=>proposal(row));}
export async function loadProposal(id:string){const[{data,error},{data:rows,error:lineError}]=await Promise.all([supabase.from('proposals').select('*').eq('id',id).single(),supabase.from('proposal_lines').select('*').eq('proposal_id',id).order('display_order')]);if(error)throw error;if(lineError)throw lineError;return proposal(data,(rows??[]).map((row)=>line(row)));}
export async function createProposal(jobId:string){const{data,error}=await supabase.rpc('create_job_proposal',{p_job_id:jobId});if(error)throw error;return String(data);}
export async function createGenericProposal(){const{data,error}=await supabase.rpc('create_proposal');if(error)throw error;return String(data);}
export async function saveProposal(value:Proposal){const lines=value.lines.map((item)=>({line_type:item.lineType,item_number:item.itemNumber,description:item.description,ref:item.ref,color_plate:item.colorPlate,quantity:item.quantity,unit:item.unit,length:item.length,width:item.width,height_thickness:item.heightThickness,cft:item.cft,lf:item.lf,estimated_weight:item.estimatedWeight,rate:item.rate,total:item.total,source_metadata:item.sourceMetadata}));const currentFields:Record<string,unknown>={projectName:value.projectName,projectLocation:value.projectLocation,projectNumber:value.projectNumber,customerName:value.customerName};const fieldSources=Object.fromEntries(Object.entries(value.fieldSources).filter(([key,evidence])=>currentFields[key]===evidence.value));const{error}=await supabase.rpc('save_proposal_draft',{p_proposal:{id:value.id,proposal_date:value.proposalDate,customer_name:value.customerName,customer_address:value.customerAddress,customer_contact:value.customerContact,project_name:value.projectName,project_number:value.projectNumber,project_location:value.projectLocation,side_mark:value.sideMark,sales_rep:value.salesRep,terms:value.terms,valid_days:value.validDays,requested_delivery:value.requestedDelivery,fob:value.fob,destination_zip:value.destinationZip,tax_county:value.taxCounty,submitted_by_name:value.submittedByName,submitted_by_phone:value.submittedByPhone,submitted_by_email:value.submittedByEmail,notes:value.notes,disclaimer_snapshot:value.disclaimerSnapshot,formula_snapshot:value.formulaSnapshot,proposal_field_sources:fieldSources,tax_enabled:value.taxEnabled,tax_rate:value.taxRate},p_lines:lines});if(error)throw error;const{error:clarificationError}=await supabase.rpc('save_proposal_clarifications',{p_proposal:{id:value.id,freight_estimate:value.freightEstimate,preliminary_drawings_attached:value.preliminaryDrawingsAttached,crating_included:value.cratingIncluded,cut_tickets_included:value.cutTicketsIncluded,field_dimensioning_excluded:value.fieldDimensioningExcluded}});if(clarificationError)throw clarificationError;}
export async function issueProposal(id:string){const{error}=await supabase.rpc('issue_proposal',{p_proposal_id:id});if(error)throw error;}
export async function createProposalRevision(id:string){const{data,error}=await supabase.rpc('create_proposal_revision',{p_proposal_id:id});if(error)throw error;return String(data);}
async function functionError(error:unknown):Promise<never>{if(error&&typeof error==='object'&&'context'in error&&error.context instanceof Response){const body=await error.context.clone().json().catch(()=>({})) as{error?:string};if(body.error)throw new Error(body.error);}throw error;}
export async function previewProposal(value:Proposal){const{data,error}=await supabase.functions.invoke('generate-proposal-pdf',{body:{action:'preview',snapshot:{...value,lines:value.lines}}});if(error)await functionError(error);if(data instanceof Blob)return data;if(data instanceof ArrayBuffer)return new Blob([data],{type:'application/pdf'});throw new Error('Proposal preview returned an invalid PDF.');}
export async function generateProposalPdf(id:string){const{data,error}=await supabase.functions.invoke('generate-proposal-pdf',{body:{action:'generate',proposalId:id}});if(error)await functionError(error);if(!data?.url)throw new Error(String(data?.error||'Proposal PDF was not generated.'));return String(data.url);}
export async function getProposalPdfUrl(id:string){const{data,error}=await supabase.functions.invoke('generate-proposal-pdf',{body:{action:'open',proposalId:id}});if(error)await functionError(error);if(!data?.url)throw new Error(String(data?.error||'Proposal PDF is unavailable.'));return String(data.url);}
export async function deleteIssuedProposal(id:string){const{data,error}=await supabase.functions.invoke('generate-proposal-pdf',{body:{action:'delete',proposalId:id}});if(error)await functionError(error);if(data?.deleted!==true)throw new Error(String(data?.error||'Proposal was not deleted.'));}
export async function deleteDraftProposal(id:string){const{error}=await supabase.rpc('delete_proposal_draft',{p_proposal_id:id});if(error)throw error;}
