import assert from 'node:assert/strict';
import { RecentThreads } from '../src/modules/my-work/messaging/recentThreads';
import type { InboxMessage } from '../src/modules/my-work/inbox';
const cache = new RecentThreads();
const rows = (peer: string, count = 41) => Array.from({length: count}, (_, n) => ({ id: String(n),senderUserId:'alice',recipientUserId:peer,attachments:[],body:'private' } as unknown as InboxMessage));
cache.reset('alice'); cache.put('alice','bob',rows('bob'),false);
assert.equal(cache.get('alice','bob')?.messages.length,40);
assert.equal(cache.get('alice','bob')?.messages[0].id,'1');
assert.equal(cache.get('alice','bob')?.hasOlder,true);
assert.equal(cache.get('outsider','bob'),undefined);
cache.put('alice','guessed',rows('bob'),false);
assert.equal(cache.get('alice','guessed'),undefined);
for(let n=0;n<4;n++)cache.put('alice',String(n),rows(String(n)),false);
cache.get('alice','bob'); cache.put('alice','next',rows('next'),false);
assert.equal(cache.get('alice','0'),undefined,'least recently used peer evicted');
assert.ok(cache.get('alice','bob'));
cache.reset('other'); assert.equal(cache.get('alice','bob'),undefined); assert.equal(cache.get('other','bob'),undefined);
cache.put('alice','bob',rows('bob'),false); assert.equal(cache.get('other','bob'),undefined,'late old-account completion cannot populate new owner');
cache.reset('alice');cache.put('alice','bob',rows('bob'),false);cache.clear();assert.equal(cache.get('alice','bob'),undefined);
console.log('PASS recent cache: owner isolation, logout clear, participant defense, 5-peer LRU, 40-row bound, late old-owner rejection.');
