import assert from 'node:assert/strict';
import { IntentPrefetch } from '../src/modules/my-work/messaging/intentPrefetch';
import { RecentThreads } from '../src/modules/my-work/messaging/recentThreads';
import type { InboxMessage } from '../src/modules/my-work/inbox';
const wait = () => new Promise(resolve => setTimeout(resolve, 120));
const cache = new RecentThreads();
let calls = 0;
let complete!: (rows: InboxMessage[]) => void;
const rows = [{ id: 'one', senderUserId: 'alice', recipientUserId: 'bob', attachments: [] }] as unknown as InboxMessage[];
const intent = new IntentPrefetch(cache, () => { calls++; return new Promise(resolve => { complete = resolve; }); });
const reset = (owner: string) => { cache.reset(owner); intent.reset(owner); };
reset('alice');
intent.intent('alice','bob'); intent.cancel(); await wait(); assert.equal(calls,0,'brief hover does no work');
intent.intent('alice','bob'); await wait(); assert.equal(calls,1);
const selected = intent.take('alice','bob'); assert.ok(selected,'click adopts in-flight history');
intent.intent('alice','carol'); await wait(); assert.equal(calls,1,'bounded concurrency');
complete(rows); await selected; await wait(); assert.equal(cache.get('alice','bob'),undefined,'stale intent not retained');
intent.intent('alice','bob'); await wait(); complete(rows); await wait(); assert.equal(cache.get('alice','bob')?.messages.length,1);
intent.intent('alice','bob'); await wait(); assert.equal(calls,2,'warm row causes no speculative read');
reset('other');reset('alice');
intent.intent('alice','bob'); await wait(); const old=complete;
reset('other');reset('alice'); assert.equal(intent.take('alice','bob'),undefined,'ABA account switch rejects old request');
old(rows);await wait();assert.equal(cache.get('alice','bob'),undefined);
intent.intent('alice','guessed');await wait();complete(rows);await wait();assert.equal(cache.get('alice','guessed'),undefined,'wrong participant rows rejected');
intent.intent('alice','guessed');await wait();complete([]);await wait();assert.equal(cache.get('alice','guessed'),undefined,'unauthorized empty result not cached');
intent.intent('alice','bob');await wait();reset('');complete(rows);await wait();assert.equal(cache.get('alice','bob'),undefined,'logout discards completion');
console.log('PASS intent prefetch: debounce, one flight, adoption, canceled intent, warm skip, ABA identity isolation, participant rejection, empty denial, logout.');
