import assert from 'node:assert/strict';
import { applyOperationalProfile, captureOperationalProfile, missingProfileInputs, operationalProfileLabel, type OperationalProfile } from '../src/modules/samples/operational-profile-model';
import { calculateSampleFormulation, standardFormulationState, previewIncreasedFillerAdjustment, resolveSupplierRatio } from '../src/modules/samples/formulation';
import { allocationError } from '../src/modules/purchasing/allocation-model';
import { createPurchaseOrderMaterialLine } from '../src/modules/purchasing/defaults';
import { buildPurchaseOrderPdfModel } from '../supabase/functions/_shared/purchase-order-pdf-model.mjs';
import { buildSamplePdfModel } from '../supabase/functions/_shared/sample-work-order-pdf-model.mjs';
const mtt: OperationalProfile={id:'test-mtt',revision:1,name:'MTT',sort_order:10,is_active:true,chip_density:128,dry_pool_rate:2560,filler_rate:512,resin_rate:480,resin_parts:5,hardener_parts:1,description:'TEST approved defaults'};
const cement={...mtt,id:'test-cement',name:'Cement',chip_density:null,dry_pool_rate:null,filler_rate:null,resin_rate:null,resin_parts:null,hardener_parts:null};
assert.equal(operationalProfileLabel(cement),'Cement — ?');assert.equal(missingProfileInputs(cement).length,5);
const original=standardFormulationState();const before=structuredClone(original);
assert.throws(()=>applyOperationalProfile(original,cement),/Draft has not been changed/);assert.deepEqual(original,before);
const state=applyOperationalProfile(original,mtt);
const aggregate={percentage:'100',quantity:'',unit:'oz',componentRole:'aggregate' as const,calculationBasis:'target_total' as const,quantityProvenance:'calculated' as const};
const filler={percentage:'',quantity:'',unit:'oz',componentRole:'filler' as const,calculationBasis:null,quantityProvenance:'calculated' as const};
const resin={...filler,unit:'fl oz',componentRole:'resin' as const},hardener={...resin,componentRole:'hardener' as const};
const rows=[aggregate,filler,resin,hardener],result=calculateSampleFormulation(state,rows);
assert.deepEqual(result.rows.map(row=>row.effectiveQuantity),['64','16','15','3']);
assert.equal(calculateSampleFormulation(state,[aggregate,{...filler,quantity:'24',quantityProvenance:'manual'},resin,hardener]).availableChipMixOz,'64');
assert.equal(previewIncreasedFillerAdjustment(state,rows,'20')?.resultingChipMixOz,'60');
assert.equal(calculateSampleFormulation({...state,materialDensity:'120'},rows).availableChipMixOz,'60');
const manual=applyOperationalProfile({...state,ratioProvenance:'manual',resinParts:'4',hardenerParts:'1'},mtt);assert.equal(manual.resinParts,'4');
assert.equal(applyOperationalProfile(state,{...mtt,name:'Sherwin',resin_parts:4,resin_rate:512}).resinParts,'4');
for(const supplier of ['Key','Key Resin','Terroxy','MTT'])assert.equal(resolveSupplierRatio(supplier,state),'5:1');assert.equal(resolveSupplierRatio('Sherwin-Williams',state),'4:1');
const captured=captureOperationalProfile(mtt);const saved=structuredClone(captured);mtt.name='Future';mtt.chip_density=130;mtt.revision++;assert.deepEqual(captured,saved);
const sheet=buildSamplePdfModel({formulation:{...state,derived:result},blendRows:rows});assert.match(JSON.stringify(sheet),/MTT/);assert.doesNotMatch(JSON.stringify(sheet),/Future/);
for(const material of ['chip','resin','pigment','filler','other'] as const){const line=createPurchaseOrderMaterialLine(material,1);line.details.quantityOrdered='2000';assert.equal(allocationError(line),'');line.allocations=[{productionJobId:'a',quantity:'1200'},{productionJobId:'b',quantity:'500'}];assert.equal(allocationError(line),'');line.details.quantityOrdered='1699';assert.match(allocationError(line),/exceed/);line.details.quantityOrdered='2000';line.allocations[1].productionJobId='a';assert.match(allocationError(line),/one allocation/);}
const poLine={line_number:1,material:'TEST Marble',quantity:2000,unit:'lb',unit_price:2,line_total:4000,line_kind:'chip'};
assert.deepEqual(buildPurchaseOrderPdfModel({po_number:'TEST-1'},[poLine]),buildPurchaseOrderPdfModel({po_number:'TEST-1',reservation_allocation_version:1},[{...poLine,reservation_allocations:[{production_job_id:'a',quantity:1200,job_name:'INTERNAL JOB'}]}]));
console.log('Managed-profile defaults/incomplete/manual/capture/V4/Working Sheet and mixed-material allocation/PDF-isolation model checks passed.');
