import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
async function verify(){
const[migration,enrichment,attachments,page,queries,notifications,arrival,inspector,nav,theme,hero]=await Promise.all([
 read('supabase/migrations/20260827_012_my_work_mvp.sql'),read('supabase/migrations/20260828_013_my_work_enrichment.sql'),read('supabase/migrations/20260831_015_my_work_task_attachments.sql'),read('src/modules/my-work/MyWorkPage.tsx'),read('src/modules/my-work/queries.ts'),read('src/components/AccountNotifications.tsx'),read('src/components/notification-arrival-state.ts'),read('src/modules/production/components/ProductionJobInspector.tsx'),read('src/app/client-layout-shell.tsx'),read('src/app/globals.css'),read('src/components/WelcomeHero.tsx'),
]);

assert.match(migration,/visibility text not null check \(visibility in \('private','shared'\)\)/);
assert.match(migration,/work_tasks_private_owner check \(visibility = 'shared' or creator_user_id = assignee_user_id\)/);
assert.match(migration,/work_tasks_shared_participants check \(visibility = 'private' or creator_user_id <> assignee_user_id\)/);
assert.match(migration,/create policy work_tasks_participant_select[\s\S]*assignee_user_id=auth\.uid\(\) or \(visibility='shared' and creator_user_id=auth\.uid\(\)\)/,'RLS must expose private tasks only to their owner and shared tasks only to participants');
assert.match(migration,/revoke all on public\.work_tasks from public,anon,authenticated;[\s\S]*grant select on public\.work_tasks to authenticated/,'clients may read participant-scoped rows but must mutate through guarded RPCs');
assert.match(migration,/where exists\(select 1 from public\.app_users actor where actor\.user_id=auth\.uid\(\) and actor\.is_active\)[\s\S]*t\.assignee_user_id=auth\.uid\(\) or \(t\.visibility='shared' and t\.creator_user_id=auth\.uid\(\)\)/,'task list RPC must repeat the participant boundary');
assert.match(migration,/if p_assignee_user_id is null or p_assignee_user_id=auth\.uid\(\)[\s\S]*task_visibility:='private'/);
assert.match(migration,/task_visibility:='shared'/);
assert.match(migration,/shared-task-assigned:[\s\S]*shared_task_assigned/);
assert.match(migration,/shared-task-completed:[\s\S]*shared_task_completed/);
assert.match(migration,/task\.creator_user_id<>auth\.uid\(\)/,'private/self completion must not notify the actor');
assert.match(migration,/context_type text[\s\S]*context_id uuid[\s\S]*context_type is null or context_type = 'job'/,'context pair must be extensible while only Job is accepted today');
assert.match(enrichment,/alter table public\.work_tasks add column notes text not null default ''/);
assert.match(enrichment,/create table public\.work_task_preferences/);
assert.match(enrichment,/primary key \(task_id,user_id\)/,'task color must be user-specific');
assert.match(enrichment,/work_task_preferences_self_select[\s\S]*user_id=auth\.uid\(\)[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'task preferences must remain self-owned and participant-scoped');
assert.match(enrichment,/left join public\.work_task_preferences preference on preference\.task_id=t\.id and preference\.user_id=auth\.uid\(\)/);
assert.match(enrichment,/create function public\.update_my_work_task/);
assert.match(enrichment,/Only the task creator can change sharing/);
assert.match(enrichment,/shared-task-assigned:/,'reassignment must preserve assignment notification behavior');
assert.match(attachments,/create table public\.work_task_attachments/);assert.match(attachments,/references public\.work_tasks\(id\) on delete cascade/);assert.match(attachments,/insert into storage\.buckets \(id, name, public[\s\S]*'my-work-attachments',[\s\S]*false/,'attachment bucket must remain private');
assert.match(attachments,/work_task_attachments_participant_select[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'metadata reads must be participant-scoped without an Admin bypass');
assert.match(attachments,/my_work_attachment_object_select[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'private objects must use the same participant boundary');
assert.match(attachments,/create function public\.create_my_work_task_complete[\s\S]*return created_id;[\s\S]*create function public\.finalize_my_work_task_creation/,'complete task creation and notification finalization must remain separate');
assert.match(attachments,/attachment_count<>p_expected_attachment_count[\s\S]*shared-task-assigned:/,'assignment notification must wait for the expected attachment metadata');
assert.match(page,/placeholder="What needs to get done\?"/);assert.match(page,/event\.key === "Enter"/);assert.match(page,/Your tasks, all in one place\./);assert.match(page,/All Tasks/);assert.match(page,/My Tasks/);assert.match(page,/Shared Tasks/);assert.match(page,/<Handshake/);assert.match(page,/h-\[18px\] w-\[18px\]/,'Handshake must remain optically legible');assert.match(page,/Completed \(\{completed\.length\}\)/);assert.match(page,/h-11 w-11/,'completion control must retain a comfortable mobile target');assert.match(page,/max-w-\[1120px\]/);assert.match(page,/grid-rows-\[0fr\]/,'completion must collapse smoothly after in-place feedback');assert.match(page,/await wait\(300\)/);assert.match(page,/What do you need to remember\?/);assert.doesNotMatch(page,/My task color/);assert.match(page,/>Color<\/div><ColorPicker/);assert.match(page,/role="combobox"/);assert.match(page,/event\.key === "ArrowDown"/);assert.match(page,/event\.key === "Escape"/);assert.match(page,/tenops_my_work_sort:/);assert.match(page,/value: "attention", label: "Recommended"/,'Recommended must remain label-only over the persisted attention key');assert.doesNotMatch(page,/label: "Attention"/);assert.match(page,/sortMode === "attention" \|\| sortMode === "due"/,'Recommended must retain the existing attention ordering algorithm');assert.match(page,/Recently Added/);assert.doesNotMatch(page,/table|kanban|priority|blocked/i);
assert.match(page,/const \[completedOpen, setCompletedOpen\] = useState\(true\)/,'Completed tasks must start expanded without changing persistence or task data');
assert.match(page,/<NotebookPen className="h-3\.5 w-3\.5" \/>Notes<\/span><textarea value=\{notes\}/,'composer Notes must use the standard standalone field label');assert.doesNotMatch(page,/Details the recipient should have before opening the task/);assert.match(page,/md:grid-cols-\[180px_minmax\(0,1fr\)_240px\]/,'composer fields must give Job the flexible desktop width');assert.match(page,/Add attachments/);assert.match(page,/accept=\{attachmentAccept\}/);assert.match(page,/await uploadWorkTaskAttachments\(id,stagedFiles\); await finalizeWorkTaskCreation\(id,stagedFiles\.length\)/,'new Shared Task notification must follow attachment association');
assert.match(page,/\['today','Today'\]/);assert.match(page,/dueBucket\(task,7\)/);assert.match(page,/\['overdue','Overdue'\],\['today','Today'\],\['upcoming','Upcoming'\]/);assert.match(page,/view!==\'today\'&&<label[\s\S]*<option value="none">None<\/option><option value="due">Due Date<\/option><option value="job">Job<\/option>/,'Today must suppress the separate grouping control');assert.match(page,/task\.attachmentCount>0/);assert.match(page,/No Job/);assert.match(page,/days === 1[\s\S]*Tomorrow/);
assert.match(page,/flex-nowrap overflow-x-auto[\s\S]*\[&::\-webkit-scrollbar\]:hidden/,'mobile view tabs must remain in one contained scroll row');assert.match(page,/scrollIntoView\(\{behavior:"smooth",block:"nearest",inline:"center"\}\)/);assert.match(page,/visualCompleted\?"text-slate-400":due\.className/,'completed due state must be visually muted');assert.match(page,/mt-8 border-t-2 border-slate-400 pt-2/,'Completed needs a stronger boundary than task cards');
assert.match(page,/hideJob:groupMode==='job'/);assert.match(page,/hideDue:groupMode==='due'/);assert.match(page,/hideDue:section\.key!==\'upcoming\'/);assert.match(page,/bg-cyan-500[\s\S]*bg-emerald-600/,'Teal and Green must be perceptually distinct without changing stored keys');
assert.doesNotMatch(page,/Notes <span className="font-normal text-slate-400">optional|Job <span className="font-normal text-slate-400">optional/);assert.match(page,/title="Color is personal to your workspace/);assert.doesNotMatch(page,/No attachments\./);assert.match(page,/Photos, PDFs, and Office files · 25 MB max/);
assert.match(queries,/p_context_type:input\.jobId\?'job':null/);assert.match(queries,/select\('task_id'\)/);assert.match(queries,/attachmentCount:counts\.get\(row\.id\)\?\?0/);assert.match(queries,/create_my_work_task_complete/);assert.match(queries,/finalize_my_work_task_creation/);assert.match(queries,/work_task_attachments/);assert.match(queries,/createSignedUrl/);assert.match(queries,/update_my_work_task/);assert.match(queries,/set_my_work_task_completed/);assert.match(inspector,/myOpenTaskCount>0/);assert.match(inspector,/View my tasks for this Job/);assert.match(nav,/href="\/my-work"[\s\S]*data-account-identity/,'My Work must sit on the account side of the header divider');
assert.match(theme,/html\[data-appearance="dark"\] \[data-my-work\] ::selection/);assert.doesNotMatch(page,/completed\.map\(taskCard\)[\s\S]{0,30}opacity-/,'completed text must not inherit compositor opacity');
assert.match(hero,/data-dev-branding=\{BRANDING\.showDeveloperArtwork/);assert.match(theme,/--tendev-signature-pink/);assert.match(theme,/data-welcome-progress-fill/);
assert.match(notifications,/notification_type\.startsWith\("shared_task_"\)/);assert.match(notifications,/router\.push\(`\/my-work\?view=shared&taskId=/);assert.match(arrival,/"shared_task_assigned"/);assert.match(arrival,/"shared_task_completed"/);
console.log('My Work MVP checks passed.');
}
void verify();
