import assert from 'node:assert/strict';
import {applyFormulationProfile,calculateSampleFormulation,previewIncreasedFillerAdjustment,SAMPLE_FORMULATION_PROFILES,standardFormulationState} from '../src/modules/samples/formulation';

const aggregate=(percentage:string)=>({percentage,quantity:'',unit:'oz',componentRole:'aggregate' as const,calculationBasis:'target_total' as const,quantityProvenance:'calculated' as const});
const rows=(filler='18',resin='15')=>[aggregate('40'),aggregate('30'),aggregate('20'),aggregate('5'),aggregate('5'),{percentage:'',quantity:filler,unit:'oz',componentRole:'filler' as const,calculationBasis:null,quantityProvenance:'manual' as const},{percentage:'',quantity:resin,unit:'fl oz',componentRole:'resin' as const,calculationBasis:null,quantityProvenance:'manual' as const},{percentage:'',quantity:'',unit:'fl oz',componentRole:'hardener' as const,calculationBasis:null,quantityProvenance:'calculated' as const}];
const state=standardFormulationState();
const standard=calculateSampleFormulation(state,rows());assert.deepEqual([standard.availableChipMixOz,standard.rows[7].effectiveQuantity],['64','3']);
const filler=calculateSampleFormulation(state,rows('22'));assert.equal(filler.availableChipMixOz,'64');assert.equal(filler.dryPoolVarianceOz,'4');assert.deepEqual(filler.rows.slice(0,5).map(row=>row.effectiveQuantity),['25.6','19.2','12.8','3.2','3.2']);
const adjustment=previewIncreasedFillerAdjustment(state,rows(),'22');assert(adjustment);const coordinated=calculateSampleFormulation({...state,materialDensity:adjustment.resultingChipDensityLbCft},rows('22'));assert.deepEqual([coordinated.availableChipMixOz,coordinated.effectiveChipDensityLbCft,coordinated.dryPoolVarianceOz],['60','120','0']);
const halfState={...state,width:'6'};const half=calculateSampleFormulation(halfState,rows('9','7.5'));assert.deepEqual([half.availableChipMixOz,half.dryPoolOz],['32','41']);const increasedFiller=previewIncreasedFillerAdjustment(halfState,rows('9','7.5'),'13');assert(increasedFiller);assert.deepEqual([increasedFiller.resultingChipMixOz,increasedFiller.resultingChipDensityLbCft],['28','112']);
const resin=calculateSampleFormulation(state,rows('18','20'));assert.deepEqual([resin.availableChipMixOz,resin.rows[7].effectiveQuantity],['64','4']);
const ratio=calculateSampleFormulation({...state,resinParts:'4'},rows('18','20'));assert.deepEqual([ratio.availableChipMixOz,ratio.rows[7].effectiveQuantity],['64','5']);
const geometry=calculateSampleFormulation({...state,width:'24'},rows('36','30'));assert.equal(geometry.dryPoolOz,'164');assert.equal(geometry.availableChipMixOz,'128');assert.equal(geometry.effectiveResinFlOz,'30');
const thickness=calculateSampleFormulation({...state,thicknessIn:'0.5'},rows('24','20'));assert.equal(thickness.availableChipMixOz,'85.333333');assert.equal(thickness.effectiveChipDensityLbCft,'128');
const density=calculateSampleFormulation({...state,materialDensity:'96'},rows());assert.equal(density.availableChipMixOz,'48','corrected V4 uses effective density as the Chip authority');
const sherwin=applyFormulationProfile(state,SAMPLE_FORMULATION_PROFILES[1]);const switched=calculateSampleFormulation(sherwin,rows('16','16'));assert.deepEqual([switched.dryPoolOz,switched.availableChipMixOz,switched.effectiveResinFlOz,switched.rows[7].effectiveQuantity],['80','64','16','4']);
const customProfile={...state.profile!,id:'custom',name:'Custom',dryPoolOzPerCft:'3000',defaultFillerOzPerCft:'600',resinFlOzPerCft:'640'};const custom=calculateSampleFormulation({...state,profile:customProfile,profileProvenance:'custom'},rows('18','20'));assert.deepEqual([custom.dryPoolOz,custom.availableChipMixOz,custom.defaultResinFlOz],['93.75','64','20']);
const manual=calculateSampleFormulation(state,[{...aggregate('100'),quantity:'9',quantityProvenance:'manual',calculationBasis:null}]);assert.equal(manual.rows[0].effectiveQuantity,'9');assert.equal(manual.percentageTotal,'0');
console.log('Sample formulation dependency/reactivity matrix passed.');
