import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {formatEstimatedMinutes,normalizeEstimatedMinutes} from '../src/modules/my-work/estimated-time';

const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
async function verify(){
const[migration,enrichment,attachments,estimatedTime,page,queries,notifications,arrival,inspector,activityStrip,nav,theme,hero,toolbox,attachmentInput]=await Promise.all([
 read('supabase/migrations/20260827_012_my_work_mvp.sql'),read('supabase/migrations/20260828_013_my_work_enrichment.sql'),read('supabase/migrations/20260831_015_my_work_task_attachments.sql'),read('supabase/migrations/20260831_021_my_work_task_estimated_time.sql'),read('src/modules/my-work/MyWorkPage.tsx'),read('src/modules/my-work/queries.ts'),read('src/components/AccountNotifications.tsx'),read('src/components/notification-arrival-state.ts'),read('src/modules/production/components/ProductionJobInspector.tsx'),read('src/modules/production/components/ActivityStrip.tsx'),read('src/app/client-layout-shell.tsx'),read('src/app/globals.css'),read('src/components/WelcomeHero.tsx'),read('src/components/ToolboxLauncher.tsx'),
 read('src/modules/my-work/AttachmentFileInput.tsx'),
]);

assert.match(migration,/visibility text not null check \(visibility in \('private','shared'\)\)/);
assert.match(migration,/work_tasks_private_owner check \(visibility = 'shared' or creator_user_id = assignee_user_id\)/);
assert.match(migration,/work_tasks_shared_participants check \(visibility = 'private' or creator_user_id <> assignee_user_id\)/);
assert.match(migration,/create policy work_tasks_participant_select[\s\S]*assignee_user_id=auth\.uid\(\) or \(visibility='shared' and creator_user_id=auth\.uid\(\)\)/,'RLS must expose private tasks only to their owner and shared tasks only to participants');
assert.match(migration,/revoke all on public\.work_tasks from public,anon,authenticated;[\s\S]*grant select on public\.work_tasks to authenticated/,'clients may read participant-scoped rows but must mutate through guarded RPCs');
assert.match(migration,/where exists\(select 1 from public\.app_users actor where actor\.user_id=auth\.uid\(\) and actor\.is_active\)[\s\S]*t\.assignee_user_id=auth\.uid\(\) or \(t\.visibility='shared' and t\.creator_user_id=auth\.uid\(\)\)/,'task list RPC must repeat the participant boundary');
assert.match(migration,/if p_assignee_user_id is null or p_assignee_user_id=auth\.uid\(\)[\s\S]*task_visibility:='private'/);
assert.match(migration,/task_visibility:='shared'/);
assert.match(migration,/shared-task-assigned:[\s\S]*shared_task_assigned/);
assert.match(migration,/shared-task-completed:[\s\S]*shared_task_completed/);
assert.match(migration,/task\.creator_user_id<>auth\.uid\(\)/,'private/self completion must not notify the actor');
assert.match(migration,/context_type text[\s\S]*context_id uuid[\s\S]*context_type is null or context_type = 'job'/,'context pair must be extensible while only Job is accepted today');
assert.match(enrichment,/alter table public\.work_tasks add column notes text not null default ''/);
assert.match(enrichment,/create table public\.work_task_preferences/);
assert.match(enrichment,/primary key \(task_id,user_id\)/,'task color must be user-specific');
assert.match(enrichment,/work_task_preferences_self_select[\s\S]*user_id=auth\.uid\(\)[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'task preferences must remain self-owned and participant-scoped');
assert.match(enrichment,/left join public\.work_task_preferences preference on preference\.task_id=t\.id and preference\.user_id=auth\.uid\(\)/);
assert.match(enrichment,/create function public\.update_my_work_task/);
assert.match(enrichment,/Only the task creator can change sharing/);
assert.match(enrichment,/shared-task-assigned:/,'reassignment must preserve assignment notification behavior');
assert.match(attachments,/create table public\.work_task_attachments/);assert.match(attachments,/references public\.work_tasks\(id\) on delete cascade/);assert.match(attachments,/insert into storage\.buckets \(id, name, public[\s\S]*'my-work-attachments',[\s\S]*false/,'attachment bucket must remain private');
assert.match(attachments,/work_task_attachments_participant_select[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'metadata reads must be participant-scoped without an Admin bypass');
assert.match(attachments,/my_work_attachment_object_select[\s\S]*task\.assignee_user_id=auth\.uid\(\) or \(task\.visibility='shared' and task\.creator_user_id=auth\.uid\(\)\)/,'private objects must use the same participant boundary');
assert.match(attachments,/create function public\.create_my_work_task_complete[\s\S]*return created_id;[\s\S]*create function public\.finalize_my_work_task_creation/,'complete task creation and notification finalization must remain separate');
assert.match(attachments,/attachment_count<>p_expected_attachment_count[\s\S]*shared-task-assigned:/,'assignment notification must wait for the expected attachment metadata');
assert.match(estimatedTime,/add column estimated_minutes integer[\s\S]*between 1 and 10080/,'estimated effort must be nullable whole minutes with a bounded positive constraint');
assert.match(estimatedTime,/returns table\([\s\S]*estimated_minutes integer/);assert.match(estimatedTime,/p_estimated_minutes integer default null/g);assert.match(estimatedTime,/estimated_minutes=p_estimated_minutes/);
assert.match(estimatedTime,/assignee_user_id=auth\.uid\(\) or \(visibility='shared' and creator_user_id=auth\.uid\(\)\)/,'estimated time must reuse participant task authorization');
assert.match(page,/placeholder="What needs to get done\?"/);assert.match(page,/event\.key === "Enter"/);assert.match(page,/Your tasks, all in one place\./);assert.match(page,/All Tasks/);assert.match(page,/My Tasks/);assert.match(page,/Shared Tasks/);assert.match(page,/<Handshake/);assert.match(page,/h-\[18px\] w-\[18px\]/,'Handshake must remain optically legible');assert.match(page,/Completed \(\{completed\.length\}\)/);assert.match(page,/h-11 w-11/,'completion control must retain a comfortable mobile target');assert.match(page,/max-w-\[1120px\]/);assert.match(page,/grid-rows-\[0fr\]/,'completion must collapse smoothly after in-place feedback');assert.match(page,/await wait\(300\)/);assert.match(page,/What do you need to remember\?/);assert.doesNotMatch(page,/My task color/);assert.match(page,/>Color<\/div><ColorPicker/);assert.match(page,/role="combobox"/);assert.match(page,/event\.key === "ArrowDown"/);assert.match(page,/event\.key === "Escape"/);assert.match(page,/tenops_my_work_sort:/);assert.match(page,/value: "attention", label: "Recommended"/,'Recommended must remain label-only over the persisted attention key');assert.doesNotMatch(page,/label: "Attention"/);assert.match(page,/sortMode === "attention" \|\| sortMode === "due"/,'Recommended must retain the existing attention ordering algorithm');assert.match(page,/Recently Added/);assert.doesNotMatch(page,/>\s*(Table|Kanban|Priority|Blocked)\s*</i);
assert.match(page,/const \[completedOpen, setCompletedOpen\] = useState\(true\)/,'Completed tasks must start expanded without changing persistence or task data');
assert.match(page,/<NotebookPen className="h-3\.5 w-3\.5" \/>Notes<\/span><textarea value=\{notes\}/,'composer Notes must use the standard standalone field label');assert.doesNotMatch(page,/Details the recipient should have before opening the task/);assert.match(page,/md:grid-cols-\[160px_160px_minmax\(0,1fr\)_220px\]/,'composer fields must retain a flexible Job width alongside compact date and estimate controls');assert.match(page,/Add attachments/);assert.match(page,/<AttachmentFileInput/);assert.match(attachmentInput,/type="file" multiple accept=\{attachmentAccept\}/);assert.match(attachmentInput,/new File\(\[await file\.arrayBuffer\(\)\]/);assert.match(attachmentInput,/onFiles\(owned\)[\s\S]*finally[\s\S]*input\.value=""/,'camera files must be owned by application state before the native input resets');assert.match(page,/await uploadWorkTaskAttachments\(id,stagedFiles,[\s\S]*await finalizeWorkTaskCreation\(id,stagedFiles\.length\)/,'new Shared Task notification must follow attachment association');assert.match(page,/const nextTasks = await loadMyWorkTasks\(\);[\s\S]*setTasks\(\(current\)=>/,'task list must render from its primary query without waiting for secondary metadata');assert.match(page,/loadWorkTaskAttachmentCounts/);
assert.equal(formatEstimatedMinutes(null),null);assert.equal(formatEstimatedMinutes(undefined),null);assert.equal(formatEstimatedMinutes(Number.NaN),null);assert.equal(formatEstimatedMinutes(0),null);assert.equal(formatEstimatedMinutes(-5),null);assert.equal(formatEstimatedMinutes(5),'5m');assert.equal(formatEstimatedMinutes(60),'1h');assert.equal(formatEstimatedMinutes(75),'1h 15m');assert.equal(formatEstimatedMinutes(185),'3h 5m');assert.equal(normalizeEstimatedMinutes(20.5),null);assert.equal(normalizeEstimatedMinutes(10081),null);
assert.match(page,/EstimatedTimeInput value=\{estimatedMinutes\}/);assert.match(page,/EstimatedTimeInput value=\{detail\.estimatedMinutes\}/);assert.match(page,/step=\{1\}/);assert.match(page,/formatEstimatedMinutes\(task\.estimatedMinutes\)/,'collapsed rows must use the guarded canonical formatter');assert.doesNotMatch(page,/NaNh|NaNm|formatEstimate\(/);assert.match(page,/Estimated time: shortest first/);assert.match(page,/Estimated time: longest first/);assert.match(page,/normalizeEstimatedMinutes\(left\.estimatedMinutes\)\?\?Number\.POSITIVE_INFINITY/);assert.match(page,/groupMode==='effort'[\s\S]*label:'Quick'[\s\S]*label:'Short'[\s\S]*label:'Medium'[\s\S]*label:'Long'[\s\S]*label:'No estimate'/);
assert.match(page,/role="button" tabIndex=\{0\} onClick=\{\(event\)=>\{if\(\(event\.target as Element\)\.closest\('\[data-task-interactive\]'\)\)return;openDetails\(task\);\}\}/,'the non-interactive task-card body must open the Inspector');assert.match(page,/data-task-interactive type="button" onClick=\{\(\) => void toggle\(task\)\}/,'completion must remain isolated from the card hitbox');assert.match(page,/data-task-interactive type="button" onClick=\{\(\) => openProductionJob/,'the Job link must remain isolated from the card hitbox');
assert.match(page,/Quick actions for \$\{task\.title\}/);assert.match(page,/Change color[\s\S]*Set or change due date[\s\S]*Set or change estimated time[\s\S]*Add attachment[\s\S]*Open Job[\s\S]*Mark open/);assert.match(page,/applyQuickTaskUpdate\(task,\{color:item\.key\}\)/,'quick color must reuse the personal-color update path');assert.match(page,/task\.contextType==='job'&&<button[\s\S]*Open Job/,'Open Job must be conditional on canonical Job context');assert.match(page,/uploadWorkTaskAttachments\(task\.id,files/);assert.match(page,/void toggle\(task\)/);
assert.match(page,/data-workload-summary/);assert.match(page,/personal=workloadScope\.filter\(\(task\)=>task\.assigneeUserId===viewerId\)/,'personal workload must follow assignment rather than visibility');assert.match(page,/delegated=workloadScope\.filter\(\(task\)=>task\.visibility==='shared'&&task\.creatorUserId===viewerId&&task\.assigneeUserId!==viewerId\)/,'viewer-created delegated tasks must be classified separately exactly once');assert.match(page,/completedCount=personal\.filter/);assert.match(page,/estimatedTotal=estimated\.reduce/);assert.match(page,/estimatedCompleted=estimated\.filter/);assert.match(page,/estimatedRemaining=estimatedTotal-estimatedCompleted/);assert.match(page,/unestimated:personal\.length-estimated\.length/);assert.match(page,/Assigned to me:[\s\S]*Assigned by me:/);assert.match(page,/delegatedEstimatedRemaining/);assert.match(page,/workload\.estimatedCompleted\/workload\.estimatedTotal/,'effort progress must use only estimated tasks assigned to the viewer');
assert.match(page,/data-workload-summary[\s\S]*open<\/span>[\s\S]*aria-label="Open tasks"/,'Workload summary must render above the open-count, Group, and Sort row');
assert.match(page,/\['today','Today'\]/);assert.match(page,/dueBucket\(task,7\)/);assert.match(page,/\['overdue','Overdue'\],\['today','Today'\],\['upcoming','Upcoming'\]/);assert.match(page,/view!==\'today\'&&<label[\s\S]*<option value="none">None<\/option><option value="due">Due Date<\/option><option value="job">Job<\/option>/,'Today must suppress the separate grouping control');assert.match(page,/task\.attachmentCount>0/);assert.match(page,/No Job/);assert.match(page,/days === 1[\s\S]*Tomorrow/);
assert.match(page,/flex-nowrap overflow-x-auto[\s\S]*\[&::\-webkit-scrollbar\]:hidden/,'mobile view tabs must remain in one contained scroll row');assert.match(page,/scrollIntoView\(\{behavior:"smooth",block:"nearest",inline:"center"\}\)/);assert.match(page,/visualCompleted\?"text-slate-400":due\.className/,'completed due state must be visually muted');assert.match(page,/mt-8 border-t-2 border-slate-400 pt-2/,'Completed needs a stronger boundary than task cards');
assert.match(page,/hideJob:groupMode==='job'/);assert.match(page,/hideDue:groupMode==='due'/);assert.match(page,/hideDue:section\.key!==\'upcoming\'/);assert.match(page,/bg-cyan-500[\s\S]*bg-emerald-600/,'Teal and Green must be perceptually distinct without changing stored keys');
assert.match(page,/data-task-color=\{task\.color\}/);assert.match(theme,/html\[data-appearance="dark"\] \[data-my-work\] \[data-task-color="blue"\] \{ border-left-color: #3b82f6 !important; \}/);assert.match(theme,/data-task-color="teal"[\s\S]*data-task-color="green"/,'dark-mode personal task colors must remain distinct after global border overrides');
assert.doesNotMatch(page,/Notes <span className="font-normal text-slate-400">optional|Job <span className="font-normal text-slate-400">optional/);assert.match(page,/title="Color is personal to your workspace/);assert.doesNotMatch(page,/No attachments\./);assert.match(page,/Photos, PDFs, and Office files · 25 MB max/);
assert.doesNotMatch(page,/task\.notes && <span/,'collapsed task rows must not repeat a Notes metadata indicator');assert.match(page,/value=\{detail\.notes\}/,'task details must retain the Notes editor');
assert.match(page,/Assigned to \$\{participantName\(task\.assigneeName\)\}/);assert.match(page,/From \$\{participantName\(task\.creatorName\)\}/);assert.match(page,/With \$\{participantName\(task\.assigneeName\)\}/,'non-participant fallback must retain natural With language');assert.match(page,/const participantName = \(value: string\) => value\.trim\(\) \|\| "TenOps user"/,'relationship copy must retain canonical display names');assert.match(page,/params\.get\("newTask"\) === "1"[\s\S]*setComposerOpen\(true\)[\s\S]*setJobId\(params\.get\("newTaskJobId"\) \|\| ""\)/);assert.match(page,/params\.delete\("newTask"\)[\s\S]*params\.delete\("newTaskJobId"\)/,'one-use composer context must not survive refresh');assert.match(page,/titleInputRef\.current\?\.focus\(\)/);assert.match(page,/<input ref=\{titleInputRef\}/);
assert.match(activityStrip,/Paperclip[\s\S]*title="New task"[\s\S]*<ListTodo/,'New task action must sit immediately after Attachments');assert.match(activityStrip,/\/my-work\?newTask=1&newTaskJobId=\$\{encodeURIComponent\(job\.id\)\}/);assert.doesNotMatch(activityStrip,/createWorkTask|create_my_work_task/,'Dashboard shortcut must never persist a task');
assert.match(queries,/p_context_type:input\.jobId\?'job':null/);assert.match(queries,/select\('task_id'\)/);assert.match(queries,/attachmentCount:0/);assert.match(queries,/loadWorkTaskAttachmentCounts[\s\S]*counts\.get\(attachment\.task_id\)/);assert.match(queries,/create_my_work_task_complete/);assert.match(queries,/finalize_my_work_task_creation/);assert.match(queries,/work_task_attachments/);assert.match(queries,/createSignedUrl/);assert.match(queries,/update_my_work_task/);assert.match(queries,/set_my_work_task_completed/);assert.match(inspector,/myOpenTaskCount>0/);assert.match(inspector,/View my tasks for this Job/);assert.match(nav,/href="\/my-work"[\s\S]*data-account-identity/,'My Work must sit on the account side of the header divider');
assert.doesNotMatch(nav,/labelKey="nav\.purchasing"/,'Purchasing must not remain a global header domain');assert.doesNotMatch(nav,/<ToolboxNav|<ToolboxLauncher|ToolCase/,'Toolbox must not render in the global header');assert.match(nav,/label: 'My Work', items: \[[\s\S]*href: '\/my-work', label: 'Tasks'[\s\S]*href: '\/my-work\?inbox=1', label: 'Inbox'/,'My Work nested navigation must expose Tasks followed by Inbox');assert.match(nav,/<Link href="\/my-work"/,'My Work must remain a direct destination');assert.match(nav,/import \{ toolboxMenuSections \} from '@\/components\/ToolboxLauncher'/);assert.match(nav,/\.\.\.toolboxMenuSections/,'My Work navigation must retain the canonical tool destination definitions');assert.match(toolbox,/export const toolboxMenuSections = \[[\s\S]*label: 'Tools'[\s\S]*Proposal Generator[\s\S]*PO Generator[\s\S]*Letter of Transmittal[\s\S]*label: 'Resources'[\s\S]*Catalog/,'My Work navigation must preserve the approved tool and resource order');assert.match(page,/<ToolboxLauncher \/>/,'Toolbox must remain a My Work page utility, not global navigation');
assert.match(theme,/html\[data-appearance="dark"\] \[data-my-work\] ::selection/);assert.doesNotMatch(page,/completed\.map\(taskCard\)[\s\S]{0,30}opacity-/,'completed text must not inherit compositor opacity');
assert.match(hero,/data-dev-branding=\{BRANDING\.showDeveloperArtwork/);assert.match(theme,/--tendev-signature-pink/);assert.match(theme,/data-welcome-progress-fill/);
assert.match(notifications,/notification_type\.startsWith\("shared_task_"\)/);assert.match(notifications,/router\.push\(`\/my-work\?view=shared&taskId=/);assert.match(arrival,/"shared_task_assigned"/);assert.match(arrival,/"shared_task_completed"/);
console.log('My Work MVP checks passed.');
}
void verify();
