import assert from 'node:assert/strict';
process.env.NEXT_PUBLIC_SUPABASE_URL='https://performance-fixture.invalid';
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='fixture';
const jobs=Array.from({length:1201},(_,i)=>({id:`job-${String(i).padStart(5,'0')}`,name:`Job ${i}`,job_number:`26-${i}`,production_status:i%3===0?'complete':'in_production',planned_start:'2026-09-01',planned_end:'2026-09-30',archived_at:i===1200?'2026-09-25':null,created_at:'2026-09-01',updated_at:'2026-09-25',remarks:'Detailed notes '.repeat(100),customer:'Customer'}));
const cycles=[{id:'cycle-2',job_id:jobs[0].id,sequence_number:2,production_status:'in_production',planned_start:'2026-10-01',planned_end:'2026-10-05',scope_details:'Detailed rework '.repeat(100)},{id:'cycle-1',job_id:jobs[0].id,sequence_number:1,production_status:'complete',planned_start:'2026-08-01',planned_end:'2026-08-05',scope_details:'Prior cycle'}];
const calls:{url:URL;bytes:number;rows:number}[]=[];
globalThis.fetch=async input=>{
 const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);assert.equal(url.hostname,'performance-fixture.invalid');
 let rows:Record<string,unknown>[]=url.pathname.endsWith('/jobs')?jobs:cycles;
 if(url.searchParams.get('archived_at')==='is.null')rows=rows.filter(r=>r.archived_at===null);
 if(url.searchParams.has('production_status'))rows=rows.filter(r=>!['complete','cancelled'].includes(String(r.production_status)));
 const count=rows.length,offset=Number(url.searchParams.get('offset')||0);
 rows=rows.slice(offset,offset+Math.min(137,Number(url.searchParams.get('limit')||1000)));
 const columns=url.searchParams.get('select')!.split(',');rows=rows.map(r=>Object.fromEntries(columns.map(c=>[c,r[c]])));
 const body=JSON.stringify(rows);calls.push({url,bytes:Buffer.byteLength(body),rows:rows.length});
 return new Response(body,{headers:{'content-type':'application/json','content-range':`${offset}-${offset+rows.length-1}/${count}`}});
};
const {loadProductionJobs,loadProductionScheduleJobs}=await import('../src/modules/production/jobs');
const {loadProductionJobOptions}=await import('../src/modules/production/job-options');
const {normalizePlanning}=await import('../src/modules/pre-production/planning-model');
const {productionJobsVisibleToRole,ADMIN_ONLY_PRODUCTION_FIXTURE_ID}=await import('../src/modules/production/fixture-visibility');
const full=await loadProductionJobs();const fullBytes=calls.reduce((n,c)=>n+c.bytes,0);calls.length=0;
const lean=await loadProductionScheduleJobs();const leanBytes=calls.reduce((n,c)=>n+c.bytes,0);
assert.equal(lean.length,1200);assert.equal(lean[0].production_status,'in_production');assert.equal(lean[0].planned_start,'2026-10-01');
const display=(rows:typeof lean)=>normalizePlanning([],[],rows,[]).map(r=>({key:r.key,title:r.title,start:r.start,end:r.end}));
assert.deepEqual(display(lean),display(full),'same schedule, ordering, terminal exclusion and active rework revival');
assert(leanBytes<fullBytes);assert(!('remarks' in lean[0]));
assert.equal((await loadProductionJobOptions()).length,1200);
assert.equal((await loadProductionJobOptions({includeArchived:true,orderBy:'schedule'})).length,1201);
jobs[1199].name='Renamed by another user';
assert.equal((await loadProductionJobOptions()).at(-1)?.name,'Renamed by another user','reopened references are authoritative');
assert(calls.every(c=>c.url.searchParams.get('order')?.endsWith('id.asc')));
const fixture=[{...lean[0],id:ADMIN_ONLY_PRODUCTION_FIXTURE_ID},lean[1]];
assert.equal(productionJobsVisibleToRole(fixture,'admin').length,2);assert.equal(productionJobsVisibleToRole(fixture,'lead').length,1);
console.log(JSON.stringify({pass:true,fullBytes,leanBytes,rows:lean.length,providerCap:137,coverage:'final page, archived modes, schedule identity/order, active Rework over terminal Job, role fixture visibility, fresh reopened options'}));
