'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import { Archive,BriefcaseBusiness,Camera,CheckCircle2,ChevronRight,File as FileIcon,FileText,MessageSquare,Plus,Trash2,Upload,UserRound,X } from 'lucide-react';
import DocumentViewer,{isDocumentPreviewSupported} from '@/components/documents/DocumentViewer';
import ActivityHistory from '@/components/inspector/ActivityHistory';
import BidSamplesCard from './BidSamplesCard';
import BidProposalCard from './BidProposalCard';
import { useAuth } from '@/lib/auth';
import { createBid,createBidFileUrl,createBidUpdate,loadBidActivity,loadBidFiles,loadBidOwners,loadBids,loadBidUpdates,openBidFile,permanentlyDeleteBid,removeBidFile,updateBid,uploadBidFiles } from './queries';
import type { Bid,BidActivity,BidFile,BidOwner,BidStatus,BidUpdate } from './types';

const statusLabel:Record<BidStatus,string>={active:'Active',won:'Won',lost:'Lost'};
const statusClass:Record<BidStatus,string>={active:'border-blue-200 bg-blue-50 text-blue-800',won:'border-emerald-200 bg-emerald-50 text-emerald-800',lost:'border-slate-300 bg-slate-100 text-slate-700'};
const field='mt-1 h-10 w-full rounded-sm border border-slate-300 bg-white px-2 text-base text-slate-950 outline-none transition focus:border-blue-700 focus:ring-2 focus:ring-blue-100 sm:h-9 sm:text-sm';
const label='text-xs font-bold text-slate-700';
const formatDate=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString();
const formatCreatedDate=(value:string)=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const formatFileSize=(value:number)=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;

function FutureArea({icon:Icon,title,children}:{icon:typeof FileText;title:string;children:string}){return <section className="min-h-24 rounded-sm border border-slate-200 bg-slate-50 p-3"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-slate-500"/><h3 className="text-xs font-bold uppercase tracking-[0.05em] text-slate-800">{title}</h3></div><p className="mt-2 text-xs leading-5 text-slate-600">{children}</p></section>}

function activityText(activity:BidActivity){const details=activity.details;if(activity.activityType==='created')return 'created this Bid';if(activity.activityType==='owner_changed')return 'reassigned the Owner';if(activity.activityType==='status_changed')return `changed status from ${String(details.from_status)} to ${String(details.to_status)}`;if(activity.activityType==='deposit_received_changed')return details.to_business_date?`recorded Deposit Received for ${formatDate(String(details.to_business_date))}`:'cleared Deposit Received';if(activity.activityType==='contact_changed')return 'updated the primary contact';if(activity.activityType==='notes_changed')return 'updated Bid Notes';if(activity.activityType==='file_added')return 'added a Bid File';if(activity.activityType==='file_removed')return 'removed a Bid File';return 'updated Bid details';}

export default function BidWorkspace(){
 const auth=useAuth();const[bids,setBids]=useState<Bid[]>([]);const[owners,setOwners]=useState<BidOwner[]>([]);const[selectedId,setSelectedId]=useState('');const[filter,setFilter]=useState<BidStatus|'all'>('active');const[creating,setCreating]=useState(false);const[customer,setCustomer]=useState('');const[projectName,setProjectName]=useState('');const[draft,setDraft]=useState<Bid|null>(null);const[activeWorkspaceTab,setActiveWorkspaceTab]=useState<'overview'|'updates'|'files'>('overview');const[activity,setActivity]=useState<BidActivity[]>([]);const[updates,setUpdates]=useState<BidUpdate[]>([]);const[updatesLoadedFor,setUpdatesLoadedFor]=useState('');const[updatesLoading,setUpdatesLoading]=useState(false);const[files,setFiles]=useState<BidFile[]>([]);const[filesLoadedFor,setFilesLoadedFor]=useState('');const[filePreview,setFilePreview]=useState<{file:BidFile;url:string}|null>(null);const[filePreviewFullscreen,setFilePreviewFullscreen]=useState(false);const[filesLoading,setFilesLoading]=useState(false);const[fileBusy,setFileBusy]=useState(false);const[removingFileId,setRemovingFileId]=useState('');const[fileError,setFileError]=useState('');const[updateBody,setUpdateBody]=useState('');const[busy,setBusy]=useState(false);const[postingUpdate,setPostingUpdate]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const refresh=useCallback(async(preferredId?:string)=>{const[nextBids,nextOwners]=await Promise.all([loadBids(),loadBidOwners()]);setBids(nextBids);setOwners(nextOwners);if(preferredId){const found=nextBids.find((bid)=>bid.id===preferredId)??null;setDraft(found);if(found)setActivity(await loadBidActivity(found.id));}return nextBids;},[]);
 useEffect(()=>{if(!auth.profile?.isActive)return;void refresh().catch((caught)=>setError(caught instanceof Error?caught.message:'Unable to load Bids.'));},[auth.profile?.isActive,refresh]);
 const visible=useMemo(()=>bids.filter((bid)=>filter==='all'||bid.status===filter),[bids,filter]);
 const previewableFiles=useMemo(()=>files.filter((file)=>isDocumentPreviewSupported(file.originalFilename,file.contentType)),[files]);
 const filePreviewIndex=filePreview?previewableFiles.findIndex((file)=>file.id===filePreview.file.id):-1;
 async function openBid(bid:Bid){setSelectedId(bid.id);setDraft(bid);setActiveWorkspaceTab('overview');setUpdates([]);setUpdatesLoadedFor('');setFiles([]);setFilesLoadedFor('');setFilePreview(null);setFilePreviewFullscreen(false);setMessage('');setError('');setFileError('');setUpdateBody('');try{setActivity(await loadBidActivity(bid.id));}catch(caught){setError(caught instanceof Error?caught.message:'Unable to load Bid workspace.');}}
 async function selectWorkspaceTab(tab:'overview'|'updates'|'files'){if(!draft)return;setActiveWorkspaceTab(tab);if(tab==='updates'&&updatesLoadedFor!==draft.id&&!updatesLoading){setUpdatesLoading(true);try{setUpdates(await loadBidUpdates(draft.id));setUpdatesLoadedFor(draft.id);}catch(caught){setError(caught instanceof Error?caught.message:'Unable to load Bid Updates.');}finally{setUpdatesLoading(false);}}if(tab==='files'&&filesLoadedFor!==draft.id&&!filesLoading){setFilesLoading(true);setFileError('');try{setFiles(await loadBidFiles(draft.id));setFilesLoadedFor(draft.id);}catch(caught){setFileError(caught instanceof Error?caught.message:'Unable to load Bid Files.');}finally{setFilesLoading(false);}}}
 async function create(){if(!customer.trim()||!projectName.trim()||busy)return;setBusy(true);setError('');try{const id=await createBid(customer,projectName);setCustomer('');setProjectName('');setCreating(false);await refresh(id);setSelectedId(id);setMessage('Bid created.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to create Bid.');}finally{setBusy(false);}}
 async function save(){if(!draft||busy)return;setBusy(true);setError('');try{await updateBid(draft);await refresh(draft.id);setMessage('Bid saved.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to save Bid.');}finally{setBusy(false);}}
 async function postUpdate(){if(!draft||!updateBody.trim()||postingUpdate)return;setPostingUpdate(true);setError('');try{await createBidUpdate(draft.id,updateBody);setUpdateBody('');setUpdates(await loadBidUpdates(draft.id));setUpdatesLoadedFor(draft.id);setMessage('Update added.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to add Update.');}finally{setPostingUpdate(false);}}
 async function uploadFiles(selected:FileList|null){if(!draft||!selected?.length||fileBusy)return;setFileBusy(true);setFileError('');try{const owned=await Promise.all([...selected].map(async(file)=>new File([await file.arrayBuffer()],file.name,{type:file.type,lastModified:file.lastModified})));await uploadBidFiles(draft.id,owned);setFiles(await loadBidFiles(draft.id));setFilesLoadedFor(draft.id);}catch(caught){setFileError(caught instanceof Error?caught.message:'Unable to upload Bid File.');}finally{setFileBusy(false);}}
 async function previewOrOpenFile(file:BidFile){setFileError('');try{if(!isDocumentPreviewSupported(file.originalFilename,file.contentType)){await openBidFile(file);return;}setFilePreview({file,url:await createBidFileUrl(file)});}catch(caught){setFileError(caught instanceof Error?caught.message:'Unable to open Bid File.');}}
 async function removeFile(file:BidFile){if(removingFileId||!window.confirm(`Remove ${file.originalFilename} from this Bid?`))return;setRemovingFileId(file.id);setFileError('');try{await removeBidFile(file);setFiles(await loadBidFiles(file.bidId));if(filePreview?.file.id===file.id){setFilePreview(null);setFilePreviewFullscreen(false);}}catch(caught){setFileError(caught instanceof Error?caught.message:'Unable to remove Bid File.');}finally{setRemovingFileId('');}}
 async function permanentlyDeleteCurrentBid(){if(!draft||busy)return;const expected=draft.projectName.trim()||'DELETE';const confirmation=window.prompt(`Permanently delete this Bid and its owned Updates, activity, and unreferenced files? This cannot be undone.\n\nType exactly: ${expected}`);if(confirmation===null)return;if(confirmation!==expected){setError('Typed confirmation did not match the Bid Project Name.');return;}setBusy(true);setError('');try{await permanentlyDeleteBid(draft.id,confirmation);setBids((current)=>current.filter((bid)=>bid.id!==draft.id));setDraft(null);setSelectedId('');setActivity([]);setUpdates([]);setFiles([]);setFilePreview(null);setFilePreviewFullscreen(false);setMessage('Bid permanently deleted.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to permanently delete Bid.');}finally{setBusy(false);}}
 return <main data-selected-bid-id={selectedId||undefined} className="min-h-[calc(100vh-73px)] bg-[#eef1f4] px-3 py-5 text-slate-950 sm:px-5"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Pre-Production</div><h1 className="mt-1 text-3xl font-bold">Bids</h1><p className="mt-1 text-sm text-slate-600">Commercial pursuits before Production handoff.</p></div><button type="button" onClick={()=>setCreating(true)} className="inline-flex min-h-10 items-center gap-2 rounded-sm border border-blue-900 bg-blue-900 px-4 text-sm font-bold text-white hover:bg-blue-800 focus-visible:ring-2 focus-visible:ring-blue-600"><Plus className="h-4 w-4"/>New Bid</button></div>
 {error&&<div role="alert" className="mt-4 border border-red-300 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}{message&&<div role="status" className="mt-4 border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}
 <div role="tablist" aria-label="Bid filters" className="mt-5 flex overflow-x-auto border-b border-slate-300">{([['active','Active'],['won','Won'],['lost','Lost'],['all','All']] as const).map(([value,text])=><button key={value} role="tab" aria-selected={filter===value} type="button" onClick={()=>setFilter(value)} className={`min-h-10 min-w-max border-b-2 px-4 text-xs font-bold uppercase tracking-[0.05em] ${filter===value?'border-slate-900 bg-slate-100/70 text-slate-950':'border-transparent text-slate-500 hover:bg-slate-50 hover:text-slate-950'}`}>{text}</button>)}</div>
 <section className="mt-3 overflow-hidden rounded-sm border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[1fr_1fr_180px_100px_36px] gap-3 border-b border-slate-200 bg-slate-50 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500 md:grid"><span>Customer</span><span>Project Name</span><span>Owner</span><span>Status</span><span/></div>{visible.length?visible.map((bid)=><button key={bid.id} type="button" onClick={()=>void openBid(bid)} className="grid min-h-14 w-full grid-cols-[1fr_auto] items-center gap-3 border-b border-slate-200 px-4 py-2.5 text-left transition last:border-b-0 hover:bg-slate-50 focus-visible:bg-blue-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-600 md:grid-cols-[1fr_1fr_180px_100px_36px]"><div className="min-w-0"><span className="block truncate font-bold md:font-semibold">{bid.customer}</span><span className="block truncate text-xs text-slate-500 md:hidden">{bid.projectName}</span></div><div className="hidden truncate text-sm text-slate-800 md:block">{bid.projectName}</div><div className="hidden truncate text-sm text-slate-600 md:block">{bid.ownerName}</div><span className={`hidden w-fit rounded-sm border px-2 py-1 text-[10px] font-bold uppercase md:inline-flex ${statusClass[bid.status]}`}>{statusLabel[bid.status]}</span><ChevronRight className="h-4 w-4 text-slate-400"/><div className="col-span-2 flex min-w-0 items-center gap-2 md:hidden"><span className={`shrink-0 rounded-sm border px-2 py-1 text-[10px] font-bold uppercase ${statusClass[bid.status]}`}>{statusLabel[bid.status]}</span><span className="truncate text-xs text-slate-500">Owner: {bid.ownerName}</span></div></button>):<div className="px-5 py-12 text-center"><Archive className="mx-auto h-7 w-7 text-slate-400"/><p className="mt-3 text-sm font-semibold text-slate-700">No Bids in this view.</p></div>}</section></div>
 {creating&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-5"><section role="dialog" aria-modal="true" aria-labelledby="new-bid-title" className="w-full border border-slate-300 bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-sm"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Pre-Production</div><h2 id="new-bid-title" className="mt-1 text-xl font-bold">New Bid</h2></div><button type="button" aria-label="Close" onClick={()=>setCreating(false)} className="flex h-9 w-9 items-center justify-center border border-slate-300 text-slate-600 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-blue-600"><X className="h-4 w-4"/></button></div><div className="mt-5 grid gap-4"><label className={label}>Customer<input autoFocus value={customer} onChange={(event)=>setCustomer(event.target.value)} maxLength={200} className={field}/></label><label className={label}>Project Name<input value={projectName} onChange={(event)=>setProjectName(event.target.value)} maxLength={300} className={field}/></label></div><p className="mt-4 text-xs text-slate-500">Owner defaults to you. New Bids begin Active. No Production Job is created.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setCreating(false)} className="min-h-10 rounded-sm border border-slate-300 px-4 text-sm font-bold hover:bg-slate-100">Cancel</button><button type="button" disabled={busy||!customer.trim()||!projectName.trim()} onClick={()=>void create()} className="min-h-10 rounded-sm border border-blue-900 bg-blue-900 px-4 text-sm font-bold text-white hover:bg-blue-800 disabled:opacity-40">{busy?'Creating…':'Create Bid'}</button></div></section></div>}
 {draft&&<div data-shell-below-header className="fixed inset-0 z-50 flex justify-end bg-slate-950/45">
  <section role="dialog" aria-modal="true" aria-labelledby="bid-workspace-title" className="ml-auto flex h-full w-full flex-col overflow-hidden border-l border-slate-200 bg-white shadow-2xl sm:max-w-3xl">
   <header className="flex shrink-0 items-start justify-between bg-white px-4 py-4 sm:px-5"><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Bid workspace</div><h2 id="bid-workspace-title" className="mt-1 truncate text-xl font-bold">{draft.customer} · {draft.projectName}</h2></div><button type="button" aria-label="Close Bid workspace" onClick={()=>{setDraft(null);setSelectedId('');setFilePreview(null);setFilePreviewFullscreen(false);}} className="ml-3 h-9 shrink-0 border border-slate-400 bg-white px-3 text-sm font-bold text-slate-700 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-blue-600">Close</button></header>
   <div role="tablist" aria-label="Bid workspace sections" className="mx-4 flex shrink-0 overflow-x-auto border-b border-slate-300 sm:mx-5">{([['overview','Overview'],['updates','Updates'],['files',`Files${files.length?` (${files.length})`:''}`]] as const).map(([value,text])=><button key={value} type="button" role="tab" id={`bid-workspace-tab-${value}`} aria-selected={activeWorkspaceTab===value} aria-controls={`bid-workspace-${value}`} onClick={()=>void selectWorkspaceTab(value)} className={`min-h-8 min-w-max flex-1 whitespace-nowrap border-b-2 px-2 py-1 text-[11px] font-bold focus-visible:z-10 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-600 ${activeWorkspaceTab===value?'border-slate-900 bg-slate-100/70 text-slate-950':'border-transparent text-slate-500 hover:bg-slate-50 hover:text-slate-950'}`}>{text}</button>)}</div>
   <div role="tabpanel" id={`bid-workspace-${activeWorkspaceTab}`} aria-labelledby={`bid-workspace-tab-${activeWorkspaceTab}`} className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-[#eef1f4] px-4 pb-4 sm:px-5 sm:pb-5">
    {activeWorkspaceTab==='overview'?<>
    <section className="mt-4 rounded-sm border border-slate-200 bg-white p-4">
     <div className="flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-blue-800"/><h3 className="text-sm font-bold uppercase tracking-[0.05em]">Overview</h3></div><p className="mt-1 text-[11px] text-slate-500">Created {formatCreatedDate(draft.createdAt)} by {draft.creatorName}</p>
     <div className="mt-4 grid gap-4 sm:grid-cols-2">
      <label className={label}>Customer<input value={draft.customer} maxLength={200} onChange={(e)=>setDraft({...draft,customer:e.target.value})} className={field}/></label>
      <label className={label}>Project Name<input value={draft.projectName} maxLength={300} onChange={(e)=>setDraft({...draft,projectName:e.target.value})} className={field}/></label>
      <label className={label}>Owner<select value={draft.ownerUserId} onChange={(e)=>setDraft({...draft,ownerUserId:e.target.value})} className={field}>{owners.map((owner)=><option key={owner.userId} value={owner.userId}>{owner.displayName}</option>)}</select></label>
      <label className={label}>Status<select value={draft.status} onChange={(e)=>setDraft({...draft,status:e.target.value as BidStatus})} className={field}><option value="active">Active</option><option value="won">Won</option><option value="lost">Lost</option></select></label>
      <label className={`${label} sm:col-span-2 sm:max-w-xs`}>Deposit Received Date<input type="date" value={draft.depositReceivedDate} onChange={(e)=>setDraft({...draft,depositReceivedDate:e.target.value})} className={field}/></label>
     </div>
     <div className="mt-5 border-t border-slate-200 pt-4"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-500"/><h4 className="text-xs font-bold uppercase tracking-[0.05em] text-slate-800">Primary Contact</h4></div><div className="mt-3 grid gap-4 sm:grid-cols-3"><label className={label}>Contact Name<input value={draft.contactName} maxLength={200} autoComplete="name" onChange={(e)=>setDraft({...draft,contactName:e.target.value})} className={field}/></label><label className={label}>Email<input type="email" value={draft.contactEmail} maxLength={320} autoComplete="email" onChange={(e)=>setDraft({...draft,contactEmail:e.target.value})} className={field}/></label><label className={label}>Phone<input type="tel" value={draft.contactPhone} maxLength={80} autoComplete="tel" onChange={(e)=>setDraft({...draft,contactPhone:e.target.value})} className={field}/></label></div></div>
     <label className={`${label} mt-5 block`}>Notes<textarea value={draft.notes} maxLength={10000} rows={5} onChange={(e)=>setDraft({...draft,notes:e.target.value})} placeholder="Persistent project, customer, or approval context" className="mt-1 w-full resize-y rounded-sm border border-slate-300 bg-white px-2 py-2 text-sm text-slate-950 outline-none transition focus:border-blue-700 focus:ring-2 focus:ring-blue-100"/></label>
     <div className="mt-4 flex justify-end border-t border-slate-200 pt-4"><button type="button" disabled={busy||!draft.customer.trim()||!draft.projectName.trim()} onClick={()=>void save()} className="min-h-10 rounded-sm border border-blue-900 bg-blue-900 px-5 text-sm font-bold text-white hover:bg-blue-800 focus-visible:ring-2 focus-visible:ring-blue-600 disabled:opacity-40">{busy?'Saving…':'Save Bid'}</button></div>
    </section>
    <div className="mt-3 grid gap-3 sm:grid-cols-3"><BidProposalCard bidId={draft.id}/><BidSamplesCard bidId={draft.id}/><FutureArea icon={CheckCircle2} title="Production">Production handoff has not occurred.</FutureArea></div>
    <div className="mt-3"><ActivityHistory title="Lifecycle history" entries={activity.map((item)=>({id:item.id,actor:item.actorName,occurredAt:item.occurredAt,content:activityText(item)}))}/></div>
    {auth.profile?.isActive&&auth.profile.role==='admin'?<section className="mt-3 border-t border-red-200 pt-4"><div className="text-xs font-bold uppercase tracking-[0.08em] text-red-800">Admin cleanup</div><p className="mt-1 text-xs text-slate-600">Exceptional cleanup for test, accidental, or duplicate Bids. This cannot be undone.</p><button type="button" disabled={busy} onClick={()=>void permanentlyDeleteCurrentBid()} className="mt-3 min-h-9 rounded-sm border border-red-400 bg-white px-3 text-sm font-bold text-red-700 hover:bg-red-50 focus-visible:ring-2 focus-visible:ring-red-600 disabled:opacity-50">Permanently delete Bid</button></section>:null}
    </>:activeWorkspaceTab==='updates'?<section className="mt-4 min-h-[calc(100%-1rem)] rounded-sm border border-slate-200 bg-white p-4">
     <div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-slate-500"/><h3 className="text-sm font-bold uppercase tracking-[0.05em]">Updates</h3></div><p className="mt-1 text-xs text-slate-500">Durable pursuit touchpoints, separate from structural lifecycle history.</p>
     <div className="mt-4 border-y border-slate-200 bg-slate-50 p-3"><label className={label}>Add Update<textarea value={updateBody} maxLength={5000} rows={4} onChange={(e)=>setUpdateBody(e.target.value)} placeholder="Customer conversation, requested revision, decision timing…" className="mt-1 w-full resize-y rounded-sm border border-slate-300 bg-white px-2 py-2 text-sm text-slate-950 outline-none transition focus:border-blue-700 focus:ring-2 focus:ring-blue-100"/></label><div className="mt-3 flex justify-end"><button type="button" disabled={postingUpdate||!updateBody.trim()} onClick={()=>void postUpdate()} className="min-h-9 rounded-sm border border-slate-900 bg-slate-900 px-4 text-sm font-bold text-white hover:bg-slate-700 focus-visible:ring-2 focus-visible:ring-blue-600 disabled:opacity-40">{postingUpdate?'Adding…':'Add Update'}</button></div></div>
     {updatesLoading?<div className="mt-4 border-y border-slate-200 py-10 text-center text-sm text-slate-500">Loading Bid Updates…</div>:updates.length?<div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{updates.map((item)=><article key={item.id} className="py-3"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-800">{item.body}</p><div className="mt-1 text-xs text-slate-500"><span className="font-semibold text-slate-700">{item.authorName}</span> · <time>{new Date(item.createdAt).toLocaleString()}</time></div></article>)}</div>:<div className="mt-4 border-y border-slate-200 py-10 text-center"><MessageSquare className="mx-auto h-5 w-5 text-slate-400"/><p className="mt-2 text-xs font-semibold text-slate-600">No Bid Updates yet.</p></div>}
    </section>:<section className="mt-4 min-h-[calc(100%-1rem)] rounded-sm border border-slate-200 bg-white p-4">
     <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-300 pb-2"><div><h3 className="text-sm font-bold uppercase tracking-[0.05em]">Files</h3><p className="mt-1 text-xs text-slate-500">Ordinary working files related to this Bid.</p></div><span className="text-xs font-semibold text-slate-500">{files.length} {files.length===1?'file':'files'}</span></div>
     <div className="mt-3 flex flex-wrap gap-2">
      <label aria-disabled={fileBusy} className={`inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-sm border border-slate-900 bg-slate-900 px-3 text-sm font-bold text-white hover:bg-slate-800 focus-within:ring-2 focus-within:ring-blue-600 ${fileBusy?'pointer-events-none opacity-50':''}`}><Upload className="h-4 w-4"/>{fileBusy?'Uploading…':'Add Files'}<input type="file" multiple disabled={fileBusy} className="sr-only" onChange={(event)=>{const input=event.currentTarget;void uploadFiles(input.files).finally(()=>{input.value='';});}}/></label>
      <label aria-disabled={fileBusy} className={`inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-sm border border-slate-300 bg-white px-3 text-sm font-bold text-slate-700 hover:bg-slate-50 focus-within:ring-2 focus-within:ring-blue-600 ${fileBusy?'pointer-events-none opacity-50':''}`}><Camera className="h-4 w-4"/>Take Photo<input type="file" accept="image/*" capture="environment" disabled={fileBusy} className="sr-only" onChange={(event)=>{const input=event.currentTarget;void uploadFiles(input.files).finally(()=>{input.value='';});}}/></label>
     </div>
     <p className="mt-2 text-[10px] text-slate-500">Files, Photo Library, and Camera are available through the device picker. Maximum 25 MB per file.</p>
     {fileError&&<div role="alert" className="mt-3 border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{fileError}</div>}
     <div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{filesLoading?<div className="px-3 py-8 text-center text-sm text-slate-500">Loading Bid Files…</div>:files.length?files.map((file)=>{const selected=filePreview?.file.id===file.id;return <div key={file.id}><div className={`flex min-w-0 items-center gap-3 py-3 ${selected?'bg-blue-50':''}`}><button type="button" onClick={()=>void previewOrOpenFile(file)} aria-pressed={selected} className="flex min-w-0 flex-1 items-center gap-3 text-left focus-visible:ring-2 focus-visible:ring-blue-600"><FileIcon className="h-5 w-5 shrink-0 text-slate-500"/><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-900" title={file.originalFilename}>{file.originalFilename}</span><span className="block truncate text-xs text-slate-500">{file.contentType} · {formatFileSize(file.byteSize)} · {formatCreatedDate(file.createdAt)} · {file.uploaderName}</span></span></button><button type="button" disabled={removingFileId===file.id} onClick={()=>void removeFile(file)} aria-label={`Remove ${file.originalFilename}`} title="Remove file" className="inline-flex h-9 w-9 shrink-0 items-center justify-center border border-slate-300 text-red-700 hover:bg-red-50 focus-visible:ring-2 focus-visible:ring-red-600 disabled:opacity-50"><Trash2 className="h-4 w-4"/></button></div>{selected&&<div className="border-t border-slate-300 p-2"><DocumentViewer key={`bid-file-embedded-${file.id}`} mode="embedded" title={`${draft.customer} · ${draft.projectName}`} filename={file.originalFilename} mimeType={file.contentType} sizeBytes={file.byteSize} metadata={`${formatCreatedDate(file.createdAt)} · ${file.uploaderName}`} url={filePreview.url} onClose={()=>setFilePreview(null)} onOpenFullscreen={()=>setFilePreviewFullscreen(true)} hasPrevious={filePreviewIndex>0} hasNext={filePreviewIndex>=0&&filePreviewIndex<previewableFiles.length-1} onPrevious={()=>{const target=previewableFiles[filePreviewIndex-1];if(target)void previewOrOpenFile(target);}} onNext={()=>{const target=previewableFiles[filePreviewIndex+1];if(target)void previewOrOpenFile(target);}}/></div>}</div>}):<div className="px-3 py-12 text-center"><FileIcon className="mx-auto h-6 w-6 text-slate-400"/><p className="mt-2 text-sm font-semibold text-slate-600">No Bid Files yet.</p><p className="mt-1 text-xs text-slate-500">Upload ordinary working files for this pursuit.</p></div>}</div>
    </section>}
   </div>
  </section>
 </div>}
 {filePreview&&filePreviewFullscreen&&<DocumentViewer key={`bid-file-fullscreen-${filePreview.file.id}`} title={draft?`${draft.customer} · ${draft.projectName}`:'Bid File'} filename={filePreview.file.originalFilename} mimeType={filePreview.file.contentType} sizeBytes={filePreview.file.byteSize} metadata={`${formatCreatedDate(filePreview.file.createdAt)} · ${filePreview.file.uploaderName}`} url={filePreview.url} onClose={()=>setFilePreviewFullscreen(false)} hasPrevious={filePreviewIndex>0} hasNext={filePreviewIndex>=0&&filePreviewIndex<previewableFiles.length-1} onPrevious={()=>{const target=previewableFiles[filePreviewIndex-1];if(target)void previewOrOpenFile(target);}} onNext={()=>{const target=previewableFiles[filePreviewIndex+1];if(target)void previewOrOpenFile(target);}}/>}
 </main>;
}
