import { supabase } from '@/lib/supabase';
import type { Bid, BidActivity, BidFile, BidOwner, BidStatus, BidUpdate } from './types';

type BidRow={id:string;customer:string;project_name:string;creator_user_id:string;creator_name:string;owner_user_id:string;owner_name:string;status:BidStatus;deposit_received_date:string|null;contact_name:string|null;contact_email:string|null;contact_phone:string|null;notes:string|null;created_at:string;updated_at:string};
const mapBid=(row:BidRow):Bid=>({id:row.id,customer:row.customer,projectName:row.project_name,creatorUserId:row.creator_user_id,creatorName:row.creator_name,ownerUserId:row.owner_user_id,ownerName:row.owner_name,status:row.status,depositReceivedDate:row.deposit_received_date??'',contactName:row.contact_name??'',contactEmail:row.contact_email??'',contactPhone:row.contact_phone??'',notes:row.notes??'',createdAt:row.created_at,updatedAt:row.updated_at});

export async function loadBids(){const{data,error}=await supabase.rpc('list_bids');if(error)throw error;return((data??[]) as BidRow[]).map(mapBid);}
export async function loadBidOwners(){const{data,error}=await supabase.rpc('list_bid_owners');if(error)throw error;return((data??[]) as Array<{user_id:string;display_name:string}>).map((row):BidOwner=>({userId:row.user_id,displayName:row.display_name}));}
export async function loadBidActivity(bidId:string){const{data,error}=await supabase.rpc('list_bid_activity',{p_bid_id:bidId});if(error)throw error;return((data??[]) as Array<{id:string;activity_type:string;actor_user_id:string;actor_name:string;occurred_at:string;details:Record<string,unknown>}>).map((row):BidActivity=>({id:row.id,activityType:row.activity_type,actorUserId:row.actor_user_id,actorName:row.actor_name,occurredAt:row.occurred_at,details:row.details??{}}));}
export async function loadBidUpdates(bidId:string){const{data,error}=await supabase.rpc('list_bid_updates',{p_bid_id:bidId});if(error)throw error;return((data??[]) as Array<{id:string;bid_id:string;author_user_id:string;author_name:string;body:string;created_at:string}>).map((row):BidUpdate=>({id:row.id,bidId:row.bid_id,authorUserId:row.author_user_id,authorName:row.author_name,body:row.body,createdAt:row.created_at}));}
export async function createBid(customer:string,projectName:string){const{data,error}=await supabase.rpc('create_bid',{p_customer:customer,p_project_name:projectName});if(error)throw error;return data as string;}
export async function updateBid(bid:Pick<Bid,'id'|'customer'|'projectName'|'ownerUserId'|'status'|'depositReceivedDate'|'contactName'|'contactEmail'|'contactPhone'|'notes'>){const{error}=await supabase.rpc('update_bid',{p_bid_id:bid.id,p_customer:bid.customer,p_project_name:bid.projectName,p_owner_user_id:bid.ownerUserId,p_status:bid.status,p_deposit_received_date:bid.depositReceivedDate||null,p_contact_name:bid.contactName,p_contact_email:bid.contactEmail,p_contact_phone:bid.contactPhone,p_notes:bid.notes});if(error)throw error;}
export async function createBidUpdate(bidId:string,body:string){const{data,error}=await supabase.rpc('create_bid_update',{p_bid_id:bidId,p_body:body});if(error)throw error;return data as string;}

const BID_FILE_BUCKET='bid-files';
type BidFileRow={id:string;bid_id:string;uploader_user_id:string;uploader_name:string;storage_path:string;original_filename:string;content_type:string;byte_size:number;created_at:string};
const mapBidFile=(row:BidFileRow):BidFile=>({id:row.id,bidId:row.bid_id,uploaderUserId:row.uploader_user_id,uploaderName:row.uploader_name,storagePath:row.storage_path,originalFilename:row.original_filename,contentType:row.content_type,byteSize:Number(row.byte_size),createdAt:row.created_at});
export async function loadBidFiles(bidId:string){const{data,error}=await supabase.rpc('list_bid_files',{p_bid_id:bidId});if(error)throw error;return((data??[]) as BidFileRow[]).map(mapBidFile);}
export async function uploadBidFiles(bidId:string,files:File[],onStage?:(stage:'preparing'|'uploading'|'finalizing')=>void){const uploaded:BidFile[]=[];for(const file of files){if(file.size>26214400)throw new Error(`${file.name} exceeds the 25 MB file limit.`);const contentType=file.type||'application/octet-stream';onStage?.('preparing');const begun=await supabase.rpc('begin_bid_file_upload',{p_bid_id:bidId,p_original_filename:file.name,p_content_type:contentType,p_byte_size:file.size});if(begun.error)throw begun.error;const prepared=(begun.data as Array<{file_id:string;storage_path:string}>|null)?.[0];if(!prepared)throw new Error('Unable to prepare Bid File upload.');try{onStage?.('uploading');const upload=await supabase.storage.from(BID_FILE_BUCKET).upload(prepared.storage_path,file,{contentType,upsert:false});if(upload.error)throw upload.error;onStage?.('finalizing');const finalized=await supabase.rpc('finalize_bid_file_upload',{p_file_id:prepared.file_id});if(finalized.error){const current=await loadBidFiles(bidId);if(!current.some((item)=>item.id===prepared.file_id))throw finalized.error;}}catch(caught){const removed=await supabase.storage.from(BID_FILE_BUCKET).remove([prepared.storage_path]);if(removed.error)throw new Error(`${caught instanceof Error?caught.message:'Unable to upload Bid File.'} Storage cleanup also failed: ${removed.error.message}`);const aborted=await supabase.rpc('abort_bid_file_upload',{p_file_id:prepared.file_id});if(aborted.error)throw new Error(`${caught instanceof Error?caught.message:'Unable to upload Bid File.'} Metadata cleanup also failed: ${aborted.error.message}`);throw caught;}const refreshed=await loadBidFiles(bidId);const created=refreshed.find((item)=>item.id===prepared.file_id);if(created)uploaded.push(created);}return uploaded;}
export async function createBidFileUrl(file:BidFile){const{data,error}=await supabase.storage.from(BID_FILE_BUCKET).createSignedUrl(file.storagePath,600);if(error)throw error;return data.signedUrl;}
export async function openBidFile(file:BidFile){const signedUrl=await createBidFileUrl(file);const link=document.createElement('a');link.href=signedUrl;link.target='_blank';link.rel='noopener noreferrer';link.download=file.originalFilename;document.body.append(link);link.click();link.remove();}
export async function removeBidFile(file:BidFile){const prepared=await supabase.rpc('prepare_bid_file_removal',{p_bid_id:file.bidId,p_file_id:file.id});if(prepared.error)throw prepared.error;const storagePath=String(prepared.data);const removed=await supabase.storage.from(BID_FILE_BUCKET).remove([storagePath]);if(removed.error){await supabase.rpc('cancel_bid_file_removal',{p_bid_id:file.bidId,p_file_id:file.id});throw removed.error;}const finalized=await supabase.rpc('finalize_bid_file_removal',{p_bid_id:file.bidId,p_file_id:file.id});if(finalized.error){const retried=await supabase.rpc('finalize_bid_file_removal',{p_bid_id:file.bidId,p_file_id:file.id});if(retried.error)throw finalized.error;}}
export async function permanentlyDeleteBid(bidId:string,confirmation:string){const prepared=await supabase.rpc('prepare_admin_delete_bid',{p_bid_id:bidId});if(prepared.error)throw prepared.error;const paths=((prepared.data??[]) as Array<{storage_path:string}>).map((row)=>row.storage_path);if(paths.length){const removed=await supabase.storage.from(BID_FILE_BUCKET).remove(paths);if(removed.error){await supabase.rpc('cancel_admin_delete_bid',{p_bid_id:bidId});throw removed.error;}}const finalized=await supabase.rpc('admin_permanently_delete_bid',{p_bid_id:bidId,p_confirmation:confirmation});if(finalized.error)throw finalized.error;}
